export interface AllahName {
  number: number
  arabic: string
  transliterationBn: string
  transliterationEn: string
  meaningBn: string
  meaningEn: string
  explanationBn: string
  category: "mercy" | "power" | "creation" | "knowledge" | "justice" | "praise"
  categoryLabelBn: string
  quranReference: string
  benefitBn: string
}

export const ALLAH_99_NAMES: AllahName[] = [
  {
    number: 1,
    arabic: "الرَّحْمَٰنُ",
    transliterationBn: "আর-রাহমান",
    transliterationEn: "Ar-Rahman",
    meaningBn: "পরম করুণাময়",
    meaningEn: "The Most Gracious / Compassionate",
    explanationBn: "যিনি সমগ্র সৃষ্টির প্রতি অসীম করুণাশীল। ঈমানদার ও কাফের নির্বিশেষে পৃথিবীর সকল সৃষ্টিকে যিনি তাঁর অনুগ্রহে লালন-পালন করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-ফাতিহা (১:৩)",
    benefitBn: "প্রতিদিন ১০০ বার পাঠ করলে অন্তরে শান্তি ও দয়া লাভ হয় এবং কঠোরতা দূর হয়।",
  },
  {
    number: 2,
    arabic: "الرَّحِيمُ",
    transliterationBn: "আর-রাহীম",
    transliterationEn: "Ar-Raheem",
    meaningBn: "পরম দয়ালু",
    meaningEn: "The Most Merciful",
    explanationBn: "যাঁর বিশেষ দয়া পরকালে কেবল তাঁর অনুগত মুমিন বান্দাদের জন্য সংরক্ষিত থাকবে।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-ফাতিহা (১:৩)",
    benefitBn: "নিয়মিত পাঠ করলে দুনিয়া ও আখিরাতে আল্লাহর বিশেষ রহমত ও ক্ষমা লাভ হয়।",
  },
  {
    number: 3,
    arabic: "الْمَلِكُ",
    transliterationBn: "আল-মালিক",
    transliterationEn: "Al-Malik",
    meaningBn: "সার্বভৌম ক্ষমতার অধিকারী / সর্বাধিপতি",
    meaningEn: "The Sovereign / The King",
    explanationBn: "সমগ্র আসমান ও যমীনের একক সার্বভৌম মালিক ও শাসক। তাঁর রাজত্ব চিরন্তন এবং কারো মুখাপেক্ষী নয়।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-হাশর (৫৯:২৩)",
    benefitBn: "ফজরের পর নিয়মিত পাঠ করলে অভাব-অনটন দূর হয় এবং আত্মমর্যাদা বৃদ্ধি পায়।",
  },
  {
    number: 4,
    arabic: "الْقُدُّوسُ",
    transliterationBn: "আল-কুদ্দুস",
    transliterationEn: "Al-Quddus",
    meaningBn: "পরম পবিত্র",
    meaningEn: "The Most Holy / Pure",
    explanationBn: "যিনি যাবতীয় ত্রুটি, দুর্বলতা, অপূর্ণতা এবং মানুষের কল্পনার ঊর্ধ্বে পরম নিখুঁত ও পবিত্র।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-জুমু'আ (৬২:১)",
    benefitBn: "অধিক পরিমাণে পাঠ করলে অন্তর আধ্যাত্মিক ব্যাধি ও অপবিত্রতা থেকে মুক্ত থাকে।",
  },
  {
    number: 5,
    arabic: "السَّلَامُ",
    transliterationBn: "আস-সালাম",
    transliterationEn: "As-Salam",
    meaningBn: "শান্তিদাতা / নিরাপত্তাদাতা",
    meaningEn: "The Source of Peace",
    explanationBn: "যিনি নিজে সকল বিপদ ও ত্রুটি থেকে মুক্ত এবং যিনি তাঁর বান্দাদের শান্তি ও নিরাপত্তা দান করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-হাশর (৫৯:২৩)",
    benefitBn: "অসুস্থ ব্যক্তির জন্য ১৬০ বার পাঠ করলে আল্লাহর ইচ্ছায় রোগমুক্তি ও সুস্থতা আসে।",
  },
  {
    number: 6,
    arabic: "الْمُؤْمِنُ",
    transliterationBn: "আল-মু'মিন",
    transliterationEn: "Al-Mu'min",
    meaningBn: "নিরাপত্তা ও ঈমানদানকারী",
    meaningEn: "The Granter of Security",
    explanationBn: "যিনি তাঁর বান্দাদের ভয় ও অশান্তি থেকে নিরাপত্তা দেন এবং সত্যবাদীদের সত্যায়িত করেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-হাশর (৫৯:২৩)",
    benefitBn: "ভয়ের সময় পাঠ করলে অন্তরে সাহস ও নিরাপত্তা তৈরি হয়।",
  },
  {
    number: 7,
    arabic: "الْمُهَيْمِنُ",
    transliterationBn: "আল-মুহাইমিন",
    transliterationEn: "Al-Muhaymin",
    meaningBn: "অভিভাবক ও রক্ষক",
    meaningEn: "The Guardian / Overseer",
    explanationBn: "যিনি সকল সৃষ্টির তত্ত্বাবধায়ক, নিয়ন্ত্রণকারী ও তাদের সকল গোপন ও প্রকাশ্য অবস্থার প্রত্যক্ষদর্শী।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আল-হাশর (৫৯:২৩)",
    benefitBn: "ওযু শেষে ১০০ বার পাঠ করলে অন্তর্দৃষ্টি আলোকিত ও প্রজ্ঞাময় হয়।",
  },
  {
    number: 8,
    arabic: "الْعَزِيزُ",
    transliterationBn: "আল-আযীয",
    transliterationEn: "Al-Aziz",
    meaningBn: "মহাপরাক্রমশালী / অপরাজিত",
    meaningEn: "The Almighty / Invulnerable",
    explanationBn: "যাঁর শক্তিমত্তা অপ্রতিদ্বন্দ্বী। যাকে কেউ পরাভূত করতে পারে না এবং যাঁর ইচ্ছার কোনো ব্যত্যয় ঘটে না।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-ইমরান (৩:৬)",
    benefitBn: "ফজরের পর ৪০ দিন নিয়মিত পাঠ করলে অন্যের উপর নির্ভরশীলতা থেকে মুক্তি পাওয়া যায়।",
  },
  {
    number: 9,
    arabic: "الْجَبَّارُ",
    transliterationBn: "আল-জাব্বার",
    transliterationEn: "Al-Jabbar",
    meaningBn: "মহাপ্রতাপশালী / সংশোধনকারী",
    meaningEn: "The Compeller / Restorer",
    explanationBn: "যিনি যা চান তা বাস্তবায়ন করেন এবং যিনি ভগ্ন হৃদয়কে জোড়া লাগান ও অভাবগ্রস্তকে পূর্ণ করেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-হাশর (৫৯:২৩)",
    benefitBn: "সকাল-সন্ধ্যায় পাঠ করলে অত্যাচারীর হাত থেকে নিরাপত্তা পাওয়া যায়।",
  },
  {
    number: 10,
    arabic: "الْمُتَكَبِّرُ",
    transliterationBn: "আল-মুতাকাব্বির",
    transliterationEn: "Al-Mutakabbir",
    meaningBn: "সর্বশ্রেষ্ঠ / অহংকারের একমাত্র যোগ্য",
    meaningEn: "The Supreme / Majestic",
    explanationBn: "প্রকৃত শ্রেষ্ঠত্ব ও অহংকার কেবল যাঁর জন্যই শোভা পায়। তিনি সকল সৃষ্টির অহংকার চূর্ণকারী।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-হাশর (৫৯:২৩)",
    benefitBn: "যেকোনো সৎ কাজ শুরুর পূর্বে পাঠ করলে সফলতার পথ সহজ হয়।",
  },
  {
    number: 11,
    arabic: "الْخَالِقُ",
    transliterationBn: "আল-খালিক্ব",
    transliterationEn: "Al-Khaliq",
    meaningBn: "একমাত্র সৃষ্টিকর্তা",
    meaningEn: "The Creator",
    explanationBn: "যিনি কোনো পূর্ব নমুনা ছাড়াই অনস্তিত্ব থেকে সমস্ত বিশ্বজাহান সৃষ্টি করেছেন।",
    category: "creation",
    categoryLabelBn: "সৃষ্টি ও প্রতিপালন",
    quranReference: "সূরা আল-আন'আম (৬:১০২)",
    benefitBn: "রাতে একনিষ্ঠভাবে পাঠ করলে অন্তরে আল্লাহভীতি ও প্রশান্তি স্থাপিত হয়।",
  },
  {
    number: 12,
    arabic: "الْبَارِئُ",
    transliterationBn: "আল-বারী",
    transliterationEn: "Al-Bari",
    meaningBn: "সুশৃঙ্খল রূপদানকারী",
    meaningEn: "The Maker of Order",
    explanationBn: "যিনি প্রতিটি বস্তুকে নিখুঁত সামঞ্জস্য এবং যথাযথ অনুপাতে অস্তিত্ব দান করেন।",
    category: "creation",
    categoryLabelBn: "সৃষ্টি ও প্রতিপালন",
    quranReference: "সূরা আল-হাশর (৫৯:২৪)",
    benefitBn: "কঠিন সংকটে নিয়মিত পাঠ করলে সকল জট ও জটিলতা সহজে সমাধান হয়।",
  },
  {
    number: 13,
    arabic: "الْمُصَوِّرُ",
    transliterationBn: "আল-মুসাওয়ির",
    transliterationEn: "Al-Musawwir",
    meaningBn: "অনুপম আকৃতিদানকারী",
    meaningEn: "The Fashioner / Shaper",
    explanationBn: "যিনি প্রতিটি সৃষ্টিকে নিজস্ব স্বতন্ত্র বৈশিষ্ট্য, সৌন্দর্য ও আকৃতি দান করেছেন।",
    category: "creation",
    categoryLabelBn: "সৃষ্টি ও প্রতিপালন",
    quranReference: "সূরা আল-হাশর (৫৯:২৪)",
    benefitBn: "সন্তান কামনাকারী দম্পতি রোজা রেখে পাঠ করলে নেক সন্তান লাভে সহায়ক হয়।",
  },
  {
    number: 14,
    arabic: "الْغَفَّارُ",
    transliterationBn: "আল-গাফফার",
    transliterationEn: "Al-Ghaffar",
    meaningBn: "পরম ক্ষমাশীল",
    meaningEn: "The Repeatedly Forgiving",
    explanationBn: "বান্দা বারবার পাপ করলেও তওবা করলে যিনি পরম করুণায় পুনরায় ক্ষমা করে দেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা ত্বা-হা (২০:৮২)",
    benefitBn: "জুমার নামাজের পর ১০০ বার পাঠ করলে গুনাহ মাফ ও মানসিক প্রশান্তি লাভ হয়।",
  },
  {
    number: 15,
    arabic: "الْقَهَّارُ",
    transliterationBn: "আল-ক্বাহহার",
    transliterationEn: "Al-Qahhar",
    meaningBn: "মহাপ্রতাপশালী পরাক্রমী",
    meaningEn: "The Subduer / Dominant",
    explanationBn: "যাঁর ক্ষমতার অধীন সমগ্র সৃষ্টিজগৎ। তিনি পরাক্রমশালী ও অহংকারীদের পদানতকারী।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা ইউসুফ (১২:৩৯)",
    benefitBn: "অন্তরের কুপ্রবৃত্তি ও শয়তানের কুমন্ত্রণা দূর করতে অত্যন্ত ফলপ্রসূ।",
  },
  {
    number: 16,
    arabic: "الْوَهَّابُ",
    transliterationBn: "আল-ওয়াহ্হাব",
    transliterationEn: "Al-Wahhab",
    meaningBn: "অবারিত মহাদাতা",
    meaningEn: "The Bestower / Giver",
    explanationBn: "যিনি কোনো প্রতিদান বা বিনিময় ছাড়াই তাঁর ভান্ডার থেকে অঢেল নিয়ামত দান করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা সাদ (৩৮:৯)",
    benefitBn: "সিজদায় গিয়ে ৭ বার পাঠ করে দু'আ করলে অভাব দূর হয় ও রিজিকে বরকত হয়।",
  },
  {
    number: 17,
    arabic: "الرَّزَّاقُ",
    transliterationBn: "আর-রায্যাক্ব",
    transliterationEn: "Ar-Razzaq",
    meaningBn: "জীবিকাদাতা",
    meaningEn: "The Provider",
    explanationBn: "যিনি স্থূল ও সূক্ষ্ম সকল সৃষ্টির শারীরিক ও আত্মিক রিযিকের একমাত্র যোগানদাতা।",
    category: "creation",
    categoryLabelBn: "সৃষ্টি ও প্রতিপালন",
    quranReference: "সূরা আয-যারিয়াত (৫১:৫৮)",
    benefitBn: "ফজরের নামাজের পূর্বে ঘরের চার কোণে ১০ বার করে পাঠ করলে রিযিকের দ্বার উন্মুক্ত হয়।",
  },
  {
    number: 18,
    arabic: "الْفَتَّاحُ",
    transliterationBn: "আল-ফাত্তাহ",
    transliterationEn: "Al-Fattah",
    meaningBn: "মহাবিজয়দাতা ও সমাধানকারী",
    meaningEn: "The Opener / Supreme Judge",
    explanationBn: "যিনি সকল বন্ধ দ্বার উন্মুক্ত করেন এবং সত্য ও মিথ্যার মাঝে ন্যায়সঙ্গত ফায়সালা করেন।",
    category: "justice",
    categoryLabelBn: "ন্যায়বিচার ও ফায়সালা",
    quranReference: "সূরা সাবা (৩৪:২৬)",
    benefitBn: "ফজরের পর বুকের উপর দুই হাত রেখে ৭১ বার পাঠ করলে অন্তরে ঈমানের নূর প্রস্ফুটিত হয়।",
  },
  {
    number: 19,
    arabic: "الْعَلِيمُ",
    transliterationBn: "আল-আলীম",
    transliterationEn: "Al-Aleem",
    meaningBn: "সর্বজ্ঞ",
    meaningEn: "The All-Knowing",
    explanationBn: "যাঁর জ্ঞানের বাইরে অতীত, বর্তমান ও ভবিষ্যতের কোনো কিছুই গোপন নেই।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আল-বাক্বারাহ (২:২৯)",
    benefitBn: "অধিক পরিমাণে পাঠ করলে ইলম, মেধা ও স্মৃতিশক্তি প্রখর হয়।",
  },
  {
    number: 20,
    arabic: "الْقَابِضُ",
    transliterationBn: "আল-ক্বাবিদ",
    transliterationEn: "Al-Qabid",
    meaningBn: "সংকোচনকারী / রুহ গ্রহণকারী",
    meaningEn: "The Constrictor",
    explanationBn: "যিনি তাঁর প্রজ্ঞায় রিযিক ও সুযোগ সংকুচিত করেন এবং মৃত্যুর সময় আত্মা কবজ করেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-বাক্বারাহ (২:২৪৫)",
    benefitBn: "নিয়মিত পাঠ করলে ক্ষুধা ও পিপাসার কষ্ট থেকে আল্লাহ রক্ষা করেন।",
  },
  {
    number: 21,
    arabic: "الْبَاسِطُ",
    transliterationBn: "আল-বাসিত",
    transliterationEn: "Al-Basit",
    meaningBn: "প্রশস্তকারী / প্রাচুর্যদাতা",
    meaningEn: "The Extender / Expander",
    explanationBn: "যিনি তাঁর অসীম দয়ায় বান্দার রিযিক, জ্ঞান ও অন্তরের স্বস্তিকে বিস্তৃত করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-বাক্বারাহ (২:২৪৫)",
    benefitBn: "চাশতের নামাজের পর হাত তুলে ১০ বার পাঠ করে মুখে হাত বুলালে সচ্ছলতা আসে।",
  },
  {
    number: 22,
    arabic: "الْخَافِضُ",
    transliterationBn: "আল-খাফিদ",
    transliterationEn: "Al-Khafid",
    meaningBn: "অবনমিতকারী",
    meaningEn: "The Reducer / Abaser",
    explanationBn: "যিনি অবাধ্য ও উদ্ধত অত্যাচারীদের লাঞ্ছিত ও নিম্নগামী করেন।",
    category: "justice",
    categoryLabelBn: "ন্যায়বিচার ও ফায়সালা",
    quranReference: "সূরা আল-ওয়াক্বি'আহ (৫৬:৩)",
    benefitBn: "শত্রুর ষড়যন্ত্র থেকে রক্ষায় প্রতিদিন ৫০০ বার পাঠ করা উপকারী।",
  },
  {
    number: 23,
    arabic: "الرَّافِعُ",
    transliterationBn: "আর-রাফি'",
    transliterationEn: "Ar-Rafi",
    meaningBn: "উন্নীতকারী / মর্যাদা দানকারী",
    meaningEn: "The Exalter / Elevator",
    explanationBn: "যিনি মুমিন ও সৎকর্মশীলদের ইহকাল ও পরকালে উচ্চ মর্যাদা দান করেন।",
    category: "justice",
    categoryLabelBn: "ন্যায়বিচার ও ফায়সালা",
    quranReference: "সূরা আল-আন'আম (৬:১৬৫)",
    benefitBn: "মাগরিবের নামাজের পর ১০০ বার পাঠ করলে সমাজে সম্মান ও মর্যাদা বৃদ্ধি পায়।",
  },
  {
    number: 24,
    arabic: "الْمُعِزُّ",
    transliterationBn: "আল-মু'ইয্যু",
    transliterationEn: "Al-Mu'izz",
    meaningBn: "সম্মানদাতা",
    meaningEn: "The Giver of Honor",
    explanationBn: "যিনি যাকে ইচ্ছা সম্মানিত করেন। প্রকৃত সম্মান ও প্রতিপত্তি কেবল আল্লাহর পক্ষ থেকেই আসে।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-ইমরান (৩:২৬)",
    benefitBn: "রবিবার বা সোমবার রাতে ১৪০ বার পাঠ করলে মানুষের কাছে শ্রদ্ধা ও ভালোবাসা লাভ হয়।",
  },
  {
    number: 25,
    arabic: "الْمُذِلُّ",
    transliterationBn: "আল-মুযিল্লু",
    transliterationEn: "Al-Mudhill",
    meaningBn: "অপমানকারী / লাঞ্ছনাকারী",
    meaningEn: "The Giver of Dishonor",
    explanationBn: "যিনি তাঁর আদেশ অমান্যকারীদের ও সীমালঙ্ঘনকারীদের উভয় জাহানে লাঞ্ছিত করেন।",
    category: "justice",
    categoryLabelBn: "ন্যায়বিচার ও ফায়সালা",
    quranReference: "সূরা আল-ইমরান (৩:২৬)",
    benefitBn: "সিজদায় ৭৫ বার পাঠ করে নিরাপত্তা চাইলে শত্রু পরাভূত হয়।",
  },
  {
    number: 26,
    arabic: "السَّمِيعُ",
    transliterationBn: "আস-সামী'",
    transliterationEn: "As-Samee",
    meaningBn: "সর্বশ্রোতা",
    meaningEn: "The All-Hearing",
    explanationBn: "যিনি প্রকাশ্য ও অতি গোপন, উচ্চ কিংবা নীরব প্রতিটি ফিসফিসানি ও মনের প্রার্থনা নিখুঁতভাবে শোনেন।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আল-বাক্বারাহ (২:১২৭)",
    benefitBn: "বৃহস্পতিবার চাশতের পর ৫০০ বার পাঠ করে দু'আ করলে তা কবুল হয়।",
  },
  {
    number: 27,
    arabic: "الْبَصِيرُ",
    transliterationBn: "আল-বাসীর",
    transliterationEn: "Al-Baseer",
    meaningBn: "সর্বদ্রষ্টা",
    meaningEn: "The All-Seeing",
    explanationBn: "যাঁর দৃষ্টির সামনে মহাবিশ্বের ক্ষুদ্রতম পরমাণু থেকে বিশাল গ্যালাক্সি পর্যন্ত সবকিছু সর্বদা স্পষ্ট।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আশ-শূরা (৪২:১১)",
    benefitBn: "জুমার সুন্নাত ও ফরজের মাঝে ১০০ বার পাঠ করলে চোখের জ্যোতি ও অন্তর্দৃষ্টি বৃদ্ধি পায়।",
  },
  {
    number: 28,
    arabic: "الْحَكَمُ",
    transliterationBn: "আল-হাকাম",
    transliterationEn: "Al-Hakam",
    meaningBn: "চূড়ান্ত বিচারক",
    meaningEn: "The Supreme Judge",
    explanationBn: "যাঁর বিচার চূড়ান্ত, নির্ভুল এবং কোনো অন্যায় বা পক্ষপাতিত্বের সুযোগ নেই।",
    category: "justice",
    categoryLabelBn: "ন্যায়বিচার ও ফায়সালা",
    quranReference: "সূরা আল-আন'আম (৬:১১৪)",
    benefitBn: "মধ্যরাতে ওযূ সহকারে ৯৯ বার পাঠ করলে অন্তরে প্রজ্ঞা ও সত্য নির্ণয়ের ক্ষমতা জন্ম নেয়।",
  },
  {
    number: 29,
    arabic: "الْعَدْلُ",
    transliterationBn: "আল-আদল",
    transliterationEn: "Al-Adl",
    meaningBn: "পরম ন্যায়পরায়ণ",
    meaningEn: "The Utterly Just",
    explanationBn: "যাঁর সকল কার্য, আদেশ ও নিষেধ ন্যায় ও সুবিচারের ওপর প্রতিষ্ঠিত। তিনি কারো ওপর অণু পরিমাণ অবিচার করেন না।",
    category: "justice",
    categoryLabelBn: "ন্যায়বিচার ও ফায়সালা",
    quranReference: "সূরা আল-আন'আম (৬:১১৫)",
    benefitBn: "শুক্রবার রাতে রুটির টুকরোয় লিখে পাঠ করলে অন্যরা সুবিচার ও বিশ্বস্ততার সাথে আচরণ করে।",
  },
  {
    number: 30,
    arabic: "اللَّطِيفُ",
    transliterationBn: "আল-লাতীফ",
    transliterationEn: "Al-Lateef",
    meaningBn: "সূক্ষ্মদর্শী ও পরম স্নেহশীল",
    meaningEn: "The Most Subtle / Kind",
    explanationBn: "যিনি অত্যন্ত সূক্ষ্ম ও অদৃশ্য উপায়ে তাঁর বান্দার প্রয়োজন পূরণ করেন এবং তাঁর প্রজ্ঞা প্রকাশ করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-হাজ্জ (২২:৬৩)",
    benefitBn: "অভাব ও বিপদের সময় ১৩৩ বার পাঠ করলে অপ্রত্যাশিতভাবে সাহায্য ও রিযিক আসে।",
  },
  {
    number: 31,
    arabic: "الْخَبِيرُ",
    transliterationBn: "আল-খাবীর",
    transliterationEn: "Al-Khabeer",
    meaningBn: "সর্ববিষয়ে সম্যক অবহিত",
    meaningEn: "The All-Aware",
    explanationBn: "যিনি সবকিছুর বাহ্যিক রূপের পাশাপাশি অভ্যন্তরীণ রহস্য ও গোপন সত্য জানেন।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আল-মুলক (৬৭:১৪)",
    benefitBn: "৭ দিন নিয়মিত পাঠ করলে গোপন কোনো বিষয় বা সমস্যা সম্পর্কে সত্য প্রকাশিত হয়।",
  },
  {
    number: 32,
    arabic: "الْحَلِيمُ",
    transliterationBn: "আল-হালীম",
    transliterationEn: "Al-Haleem",
    meaningBn: "পরম ধৈর্যশীল ও সহনশীল",
    meaningEn: "The Most Forbearing",
    explanationBn: "যিনি বান্দার অন্যায়ে দ্রুত শাস্তি দেন না, বরং সংশোধনের সুযোগ দিয়ে দীর্ঘ সময় অপেক্ষা করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-বাক্বারাহ (২:২২৫)",
    benefitBn: "কাগজে লিখে পানিতে ভিজিয়ে তা কোনো জিনিস বা ফসলে ছিটকিয়ে দিলে বিপদ থেকে রক্ষা হয়।",
  },
  {
    number: 33,
    arabic: "الْعَظِيمُ",
    transliterationBn: "আল-আযীম",
    transliterationEn: "Al-Azeem",
    meaningBn: "মহিমান্বিত ও সুমহান",
    meaningEn: "The Most Magnificent",
    explanationBn: "যাঁর মহিমা ও শ্রেষ্ঠত্ব মানুষের জ্ঞান ও বর্ণনার অতীত। তিনি যাবতীয় বড়ত্বের অধিকারী।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আশ-শূরা (৪২:৪)",
    benefitBn: "অধিক পরিমাণে পাঠ করলে মানুষের কাছে গ্রহণযোগ্যতা ও সম্মান বৃদ্ধি পায়।",
  },
  {
    number: 34,
    arabic: "الْغَفُورُ",
    transliterationBn: "আল-গাফুর",
    transliterationEn: "Al-Ghafoor",
    meaningBn: "অতিশয় ক্ষমাশীল",
    meaningEn: "The All-Forgiving",
    explanationBn: "যিনি বান্দার পাপ গোপন রাখেন এবং অনুশোচনা করলে তা সম্পূর্ণ মুছে দেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-বাক্বারাহ (২:১৭৩)",
    benefitBn: "মাথা ব্যথায় কিংবা অসুস্থতায় নিয়মিত পাঠ করলে আরোগ্য লাভ হয়।",
  },
  {
    number: 35,
    arabic: "الشَّكُورُ",
    transliterationBn: "আশ-শাকূর",
    transliterationEn: "Ash-Shakoor",
    meaningBn: "গুণগ্রাহী / মূল্যায়নকারী",
    meaningEn: "The Most Appreciative",
    explanationBn: "যিনি বান্দার সামান্য সৎকাজের বিনিময়ে বহুগুণে অফুরন্ত প্রতিদান দান করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা ফাতির (৩৫:৩০)",
    benefitBn: "চোখের দুর্বলতায় ৪১ বার পাঠ করে পানিতে ফুঁ দিয়ে চোখ ধৌত করলে উপকার হয়।",
  },
  {
    number: 36,
    arabic: "الْعَلِيُّ",
    transliterationBn: "আল-আলী",
    transliterationEn: "Al-Ali",
    meaningBn: "সর্বোচ্চ / সমুন্নত",
    meaningEn: "The Most High",
    explanationBn: "যাঁর সত্তা, গুণাবলী ও ক্ষমতা সবকিছুর ঊর্ধ্বে সমুন্নত।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-বাক্বারাহ (২:২৫৫)",
    benefitBn: "নিয়মিত পাঠ ও লিখে সাথে রাখলে সৌভাগ্য ও মর্যাদা লাভ হয়।",
  },
  {
    number: 37,
    arabic: "الْكَبِيرُ",
    transliterationBn: "আল-কবীর",
    transliterationEn: "Al-Kabeer",
    meaningBn: "মহানুভব ও সর্বশ্রেষ্ঠ",
    meaningEn: "The Most Great",
    explanationBn: "যাঁর সত্তা ও মহত্ত্বের কোনো তুলনা নেই। তিনি সর্বাপেক্ষা মহান।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আর-রাদ (১৩:৯)",
    benefitBn: "প্রতিদিন ১০০ বার পাঠ করলে জ্ঞান ও প্রজ্ঞার দরজা খুলে যায়।",
  },
  {
    number: 38,
    arabic: "الْحَفِيظُ",
    transliterationBn: "আল-হাফীয",
    transliterationEn: "Al-Hafeez",
    meaningBn: "সর্বোত্তম রক্ষক",
    meaningEn: "The Preserver / Protector",
    explanationBn: "যিনি সমগ্র আসমান, যমীন ও সমস্ত সৃষ্টিকে ধংস ও বিশৃঙ্খলা থেকে রক্ষা করেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা হুদ (১১:৫৭)",
    benefitBn: "সফর কিংবা বিপদাপদের সময় ১৬ বার পাঠ করলে আল্লাহর বিশেষ নিরাপত্তায় থাকা যায়।",
  },
  {
    number: 39,
    arabic: "الْمُقِيتُ",
    transliterationBn: "আল-মুক্বীত",
    transliterationEn: "Al-Muqeet",
    meaningBn: "সংরক্ষণকারী ও খোরাকদাতা",
    meaningEn: "The Sustainer",
    explanationBn: "যিনি প্রতিটি সৃষ্টির শারীরিক ও আত্মিক শক্তির আধার ও পুষ্টিদাতা।",
    category: "creation",
    categoryLabelBn: "সৃষ্টি ও প্রতিপালন",
    quranReference: "সূরা আন-নিসা (৪:৮৫)",
    benefitBn: "পানিতে ৭ বার ফুঁ দিয়ে খারাপ মেজাজের সন্তানকে পান করালে স্বভাব শান্ত হয়।",
  },
  {
    number: 40,
    arabic: "الْحَسِيبُ",
    transliterationBn: "আল-হাসীব",
    transliterationEn: "Al-Haseeb",
    meaningBn: "হিসাব গ্রহণকারী ও যথেষ্ট সত্তা",
    meaningEn: "The Reckoner / Sufficient",
    explanationBn: "যিনি বান্দার প্রতিটি কাজের সূক্ষ্ম হিসাব নেন এবং যার ওপর ভরসা করলে তিনিই একমাত্র যথেষ্ট।",
    category: "justice",
    categoryLabelBn: "ন্যায়বিচার ও ফায়সালা",
    quranReference: "সূরা আন-নিসা (৪:৬)",
    benefitBn: "চুরি ও ক্ষতির ভয়ে বৃহস্পতিবার থেকে শুরু করে প্রত্যহ ৭০ বার 'হাসবিয়াল্লাহুল হাসীব' পাঠ করা উপকারী।",
  },
  {
    number: 41,
    arabic: "الْجَلِيلُ",
    transliterationBn: "আল-জালীল",
    transliterationEn: "Al-Jaleel",
    meaningBn: "মহিমাময় ও প্রতাপশালী",
    meaningEn: "The Majestic / Sublime",
    explanationBn: "যাঁর মহত্ত্ব ও শান অতুলনীয়। তিনি সকল প্রকার মহৎ গুণের আধার।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আর-রহমান (৫৫:২৭)",
    benefitBn: "কাগজে লিখে সাথে রাখলে মানুষের হৃদয়ে শ্রদ্ধা ও মর্যাদা স্থাপিত হয়।",
  },
  {
    number: 42,
    arabic: "الْكَرِيمُ",
    transliterationBn: "আল-কারীম",
    transliterationEn: "Al-Kareem",
    meaningBn: "পরম দাতা ও সম্মানিত",
    meaningEn: "The Most Generous",
    explanationBn: "যিনি না চাইতেই দান করেন এবং অপরাধ ক্ষমা করে মর্যাদা বৃদ্ধি করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-ইনফিতার (৮২:৬)",
    benefitBn: "ঘুমানোর আগে পাঠ করলে আলেম ও সৎকর্মশীলদের সম্মান লাভ হয়।",
  },
  {
    number: 43,
    arabic: "الرَّقِيبُ",
    transliterationBn: "আর-রাক্বীব",
    transliterationEn: "Ar-Raqeeb",
    meaningBn: "সদা সতর্ক পর্যবেক্ষক",
    meaningEn: "The Watchful",
    explanationBn: "যাঁর নজর থেকে সৃষ্টিজগতের একটি ধূলিকণাও বাদ যায় না। তিনি মানুষের অন্তরের সংকল্পের সাক্ষী।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আন-নিসা (৪:১)",
    benefitBn: "পরিবার ও সম্পদের সুরক্ষায় ৭ বার পাঠ করে ফুঁ দিলে নিরাপত্তা লাভ হয়।",
  },
  {
    number: 44,
    arabic: "الْمُجِيبُ",
    transliterationBn: "আল-মুজীব",
    transliterationEn: "Al-Mujeeb",
    meaningBn: "প্রার্থনা কবুলকারী",
    meaningEn: "The Responsive / Answerer",
    explanationBn: "যিনি ব্যাকুল বান্দার ডাক শোনেন এবং তাঁর হিকমত অনুযায়ী দু'আ কবুল করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা হুদ (১১:৬১)",
    benefitBn: "দু'আর শেষে অধিক পরিমাণে পাঠ করলে দ্রুত দু'আ কবুল হয়।",
  },
  {
    number: 45,
    arabic: "الْوَاسِعُ",
    transliterationBn: "আল-ওয়াসি'",
    transliterationEn: "Al-Wasi",
    meaningBn: "অসীম বিস্তৃত / সর্বব্যাপী",
    meaningEn: "The All-Encompassing",
    explanationBn: "যাঁর রহমত, জ্ঞান, ক্ষমতা ও ভান্ডার সমস্ত সৃষ্টিজগতকে পরিবেষ্টন করে রেখেছে।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-বাক্বারাহ (২:১১৫)",
    benefitBn: "অভাব দূরীকরণে ও মানসিক প্রশান্তিতে নিয়মিত পাঠ করা অত্যন্ত উপকারী।",
  },
  {
    number: 46,
    arabic: "الْحَكِيمُ",
    transliterationBn: "আল-হাকীম",
    transliterationEn: "Al-Hakeem",
    meaningBn: "পরম প্রজ্ঞাময়",
    meaningEn: "The All-Wise",
    explanationBn: "যাঁর প্রতিটি কাজ প্রজ্ঞা, উদ্দেশ্য ও কল্যাণে ভরপুর। তাঁর কোনো সিদ্ধান্ত বৃথা নয়।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আল-বাক্বারাহ (২:১২৯)",
    benefitBn: "কাজে সফলতা ও সঠিক সিদ্ধান্ত গ্রহণের তৌফিক লাভে নিয়মিত পাঠ করুন।",
  },
  {
    number: 47,
    arabic: "الْوَدُودُ",
    transliterationBn: "আল-ওয়াদূদ",
    transliterationEn: "Al-Wadood",
    meaningBn: "পরম প্রেমময় ও স্নেহশীল",
    meaningEn: "The Most Loving",
    explanationBn: "যিনি তাঁর প্রিয় বান্দাদের গভীর ভালোবাসায় বেষ্টন করে রাখেন এবং তাঁদের ওপর সন্তুষ্ট থাকেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-বুরুজ (৮৫:১৪)",
    benefitBn: "স্বামী-স্ত্রীর মাঝে ভালোবাসা বৃদ্ধির জন্য ১০০০ বার খাবারের ওপর পাঠ করে খাওয়ালে কলহ দূর হয়।",
  },
  {
    number: 48,
    arabic: "الْمَجِيدُ",
    transliterationBn: "আল-মাজীদ",
    transliterationEn: "Al-Majeed",
    meaningBn: "মহিমান্বিত ও সুমহান গৌরবময়",
    meaningEn: "The Most Glorious",
    explanationBn: "যাঁর মর্যাদা ও গৌরব অনুপম এবং যাঁর দান ও অনুগ্রহ সীমাহীন।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা হুদ (১১:৭৩)",
    benefitBn: "আইয়ামে বীজের রোজার সময় পাঠ করলে শারীরিক ও আত্মিক রোগ দূর হয়।",
  },
  {
    number: 49,
    arabic: "الْبَاعِثُ",
    transliterationBn: "আল-বা'ইছ",
    transliterationEn: "Al-Ba'ith",
    meaningBn: "পুনরুজ্জীবিতকারী",
    meaningEn: "The Resurrector",
    explanationBn: "যিনি কিয়ামতের দিন কবরে শায়িত সকল মৃতকে পুনরায় জীবন দান করে হাশরে একত্রিত করবেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-হাজ্জ (২২:৭)",
    benefitBn: "ঘুমানোর সময় বুকে হাত রেখে ১০০ বার পাঠ করলে অন্তরে আল্লাহভীতি ও ঈমানের নূর জাগ্রত হয়।",
  },
  {
    number: 50,
    arabic: "الشَّهِيدُ",
    transliterationBn: "আশ-শাহীদ",
    transliterationEn: "Ash-Shaheed",
    meaningBn: "প্রত্যক্ষদর্শী ও সাক্ষী",
    meaningEn: "The Witness",
    explanationBn: "যাঁর কাছে বিশ্বজগতের কোনো দৃশ্য বা অদৃশ্য বস্তু গোপন নেই। তিনি সকল ঘটনার প্রত্যক্ষদর্শী।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আল-হাজ্জ (২২:১৭)",
    benefitBn: "অবাধ্য সন্তানের কপালে হাত রেখে ২১ বার পাঠ করলে সে আনুগত্যশীল হয়।",
  },
  {
    number: 51,
    arabic: "الْحَقُّ",
    transliterationBn: "আল-হাক্ব",
    transliterationEn: "Al-Haqq",
    meaningBn: "পরম সত্য",
    meaningEn: "The Absolute Truth",
    explanationBn: "যাঁর অস্তিত্ব চিরন্তন সত্য এবং যাঁর প্রতিশ্রুতি ও কালাম অভ্রান্ত সত্য।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আন-নূর (২৪:২৫)",
    benefitBn: "হারানো জিনিস ফিরে পেতে চার কোণা কাগজে লিখে দু'আ করলে ফিরে পাওয়া সহজ হয়।",
  },
  {
    number: 52,
    arabic: "الْوَكِيلُ",
    transliterationBn: "আল-ওয়াকীল",
    transliterationEn: "Al-Wakeel",
    meaningBn: "উত্তম কর্মবিধায়ক ও অভিভাবক",
    meaningEn: "The Trustee / Disposer",
    explanationBn: "যাঁর ওপর সমস্ত কাজের দায়িত্ব অর্পণ করা যায় এবং যিনি বান্দার জন্য সর্বোত্তম অভিভাবক।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-ইমরান (৩:১৭৩)",
    benefitBn: "প্রাকৃতিক দুর্যোগ বা ভয়ের সময় পাঠ করলে আল্লাহর পূর্ণ নিরাপত্তায় থাকা যায়।",
  },
  {
    number: 53,
    arabic: "الْقَوِيُّ",
    transliterationBn: "আল-ক্ববীয়্যু",
    transliterationEn: "Al-Qawiyy",
    meaningBn: "মহাশক্তিশালী",
    meaningEn: "The All-Strong",
    explanationBn: "যাঁর শক্তির কোনো ক্ষয় বা ক্লান্তি নেই। তিনি সমস্ত ক্ষমতার মূল উৎস।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-হাজ্জ (২২:৪০)",
    benefitBn: "শত্রুর হাত থেকে মুক্তি ও শারীরিক বলবীর্য লাভে নিয়মিত পাঠ করা ফলদায়ক।",
  },
  {
    number: 54,
    arabic: "الْمَتِينُ",
    transliterationBn: "আল-মাতীন",
    transliterationEn: "Al-Mateen",
    meaningBn: "সুদৃঢ় ও অটল",
    meaningEn: "The Firm / Steadfast",
    explanationBn: "যাঁর শক্তি এতই সুদৃঢ় যে কোনো কিছুই তাকে দুর্বল বা বিচলিত করতে পারে না।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আয-যারিয়াত (৫১:৫৮)",
    benefitBn: "দুগ্ধবতী মায়ের দুধ বৃদ্ধির জন্য পাঠ করে পানিতে ফুঁ দিয়ে পান করালে উপকার হয়।",
  },
  {
    number: 55,
    arabic: "الْوَلِيُّ",
    transliterationBn: "আল-ওয়ালী",
    transliterationEn: "Al-Waliyy",
    meaningBn: "অভিভাবক ও সাহায্যকারী বন্ধু",
    meaningEn: "The Protecting Friend",
    explanationBn: "যিনি মুমিনদের প্রিয় বন্ধু, সাহায্যকারী ও সঠিক পথের পথপ্রদর্শক।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-বাক্বারাহ (২:২৫৭)",
    benefitBn: "নিয়মিত পাঠ করলে আল্লাহর নৈকট্য ও বেলায়েতের মর্যাদা লাভ হয়।",
  },
  {
    number: 56,
    arabic: "الْحَمِيدُ",
    transliterationBn: "আল-হামীদ",
    transliterationEn: "Al-Hameed",
    meaningBn: "সর্বপ্রশংসিত",
    meaningEn: "The Praiseworthy",
    explanationBn: "যিনি তাঁর নিখুঁত সত্তা ও সৃষ্টির মাঝে সর্বদা প্রশংসার একমাত্র যোগ্য।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা ইব্রাহীম (১৪:১)",
    benefitBn: "একাকী ৯৩ বার পাঠ করলে মানুষের কাছে প্রিয় হওয়া যায় এবং চরিত্র সুন্দর হয়।",
  },
  {
    number: 57,
    arabic: "الْمُحْصِي",
    transliterationBn: "আল-মুহসী",
    transliterationEn: "Al-Muhsee",
    meaningBn: "সকল কিছুর গণনাকারী",
    meaningEn: "The Appraiser / Counter",
    explanationBn: "যিনি বিশ্বজগতের প্রতিটি বস্তুর সঠিক সংখ্যা ও হিসাব পুঙ্খানুপুঙ্খ জানেন।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা মারইয়াম (১৯:৯৪)",
    benefitBn: "প্রতিদিন ১০০ বার পাঠ করলে হাশরের ময়দানে হিসাব সহজ হয়।",
  },
  {
    number: 58,
    arabic: "الْمُبْدِئُ",
    transliterationBn: "আল-মুবদি'",
    transliterationEn: "Al-Mubdi",
    meaningBn: "প্রথম সূচনাকারী",
    meaningEn: "The Originator",
    explanationBn: "যিনি কোনো পূর্ব উপাদান ছাড়াই সবকিছুর প্রাথমিক সূচনা করেছেন।",
    category: "creation",
    categoryLabelBn: "সৃষ্টি ও প্রতিপালন",
    quranReference: "সূরা আল-বুরুজ (৮৫:১৩)",
    benefitBn: "গর্ভবতী নারীর সুরক্ষায় পেটে হাত রেখে পাঠ করলে সন্তান নিরাপদে থাকে।",
  },
  {
    number: 59,
    arabic: "الْمُعِيدُ",
    transliterationBn: "আল-মু'ঈদ",
    transliterationEn: "Al-Mu'eed",
    meaningBn: "পুনর্বার সৃষ্টিকারী",
    meaningEn: "The Restorer",
    explanationBn: "যিনি সৃষ্টির ধ্বংসের পর পুনরায় তাকে পূর্বাবস্থায় ফিরিয়ে আনবেন।",
    category: "creation",
    categoryLabelBn: "সৃষ্টি ও প্রতিপালন",
    quranReference: "সূরা আল-বুরুজ (৮৫:১৩)",
    benefitBn: "হারিয়ে যাওয়া ব্যক্তি বা সম্পদ ফিরে পেতে ৭০ বার পাঠ করা উপকারী।",
  },
  {
    number: 60,
    arabic: "الْمُحْيِي",
    transliterationBn: "আল-মুহ্​য়ী",
    transliterationEn: "Al-Muhyi",
    meaningBn: "জীবনদাতা",
    meaningEn: "The Giver of Life",
    explanationBn: "যিনি মৃত বস্তুকে প্রাণ দান করেন এবং দেহাবশেষকে সজীব করেন।",
    category: "creation",
    categoryLabelBn: "সৃষ্টি ও প্রতিপালন",
    quranReference: "সূরা আর-রূম (৩০:৫০)",
    benefitBn: "কঠিন রোগে আক্রান্ত ব্যক্তি নিয়মিত পাঠ করলে আল্লাহর ইচ্ছায় আরোগ্য লাভ করে।",
  },
  {
    number: 61,
    arabic: "الْمُمِيتُ",
    transliterationBn: "আল-মুমীত",
    transliterationEn: "Al-Mumeet",
    meaningBn: "মৃত্যুদাতা",
    meaningEn: "The Destroyer / Bringer of Death",
    explanationBn: "যিনি সকল জীবন্ত প্রাণীর নির্ধারিত সময়ে জীবনের সমাপ্তি ঘটান।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-আন'আম (৬:২)",
    benefitBn: "নিজের নফস ও কুপ্রবৃত্তিকে নিয়ন্ত্রণ করতে বুকের ওপর হাত রেখে পাঠ করুন।",
  },
  {
    number: 62,
    arabic: "الْحَيُّ",
    transliterationBn: "আল-হাইয়্যু",
    transliterationEn: "Al-Hayy",
    meaningBn: "চিরঞ্জীব",
    meaningEn: "The Ever-Living",
    explanationBn: "যাঁর জীবনের কোনো শুরু বা শেষ নেই। তিনি চিরকাল জীবিত ছিলেন, আছেন ও থাকবেন।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-বাক্বারাহ (২:২৫৫)",
    benefitBn: "দৈনিক ৩০০ বার পাঠ করলে দীর্ঘায়ু, সুস্থতা ও বরকত লাভ হয়।",
  },
  {
    number: 63,
    arabic: "الْقَيُّومُ",
    transliterationBn: "আল-ক্বাইয়্যূম",
    transliterationEn: "Al-Qayyoom",
    meaningBn: "চিরস্থায়ী ও বিশ্বজগতের ধারক",
    meaningEn: "The Self-Subsisting Sustainer",
    explanationBn: "যিনি নিজে স্বয়ংসম্পূর্ণ এবং সমগ্র বিশ্বজগতের অস্তিত্ব ও পরিচালনার একক অবলম্বন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-বাক্বারাহ (২:২৫৫)",
    benefitBn: "ফজরের পর 'ইয়া হাইয়্যু ইয়া ক্বাইয়্যূম' পাঠ করলে অলসতা দূর হয় ও জীবিকা বৃদ্ধি পায়।",
  },
  {
    number: 64,
    arabic: "الْوَاجِدُ",
    transliterationBn: "আল-ওয়াজিদ",
    transliterationEn: "Al-Wajid",
    meaningBn: "অভাবহীন / যা চান তাই প্রাপ্ত",
    meaningEn: "The Perceiver / Finder",
    explanationBn: "যাঁর কোনো কিছুর অভাব নেই এবং যাঁর কোনো চাওয়া কখনো অপূর্ণ থাকে না।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আদ-দুহা (৯৩:৬-৮)",
    benefitBn: "খাওয়ার সময় পাঠ করলে অন্তরের তৃপ্তি ও আলোকিত ভাব অনুভূত হয়।",
  },
  {
    number: 65,
    arabic: "الْمَاجِدُ",
    transliterationBn: "আল-মাজিদ",
    transliterationEn: "Al-Majid",
    meaningBn: "মহিমান্বিত ও শ্রেষ্ঠ",
    meaningEn: "The Illustrious",
    explanationBn: "যাঁর মহত্ত্ব, মর্যাদা ও দানশীলতা সমস্ত কল্পনার অতীত।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা হুদ (১১:৭৩)",
    benefitBn: "একাকী পাঠ করলে অন্তরে ঐশ্বরিক প্রশান্তি ও পবিত্রতা নেমে আসে।",
  },
  {
    number: 66,
    arabic: "الْوَاحِدُ",
    transliterationBn: "আল-ওয়াহিদ",
    transliterationEn: "Al-Wahid",
    meaningBn: "একক ও অদ্বিতীয়",
    meaningEn: "The One",
    explanationBn: "যাঁর সত্তা ও গুণে কোনো অংশীদার নেই। তিনি এক ও একক।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-বাক্বারাহ (২:১৬৩)",
    benefitBn: "১০০০ বার পাঠ করলে ভয় ও একাকীত্ব দূর হয় এবং তাওহীদের নূর প্রস্ফুটিত হয়।",
  },
  {
    number: 67,
    arabic: "الْأَحَد",
    transliterationBn: "আল-আহাদ",
    transliterationEn: "Al-Ahad",
    meaningBn: "একক লা-শরীক",
    meaningEn: "The Indivisible One",
    explanationBn: "যাঁর কোনো সন্তান নেই, পিতা-মাতা নেই এবং যাঁর সমকক্ষ কেউ নেই।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-ইখলাস (১১২:১)",
    benefitBn: "১০০০ বার পাঠ করলে গোপন রহস্যের জ্ঞান ও আধ্যাত্মিক একাগ্রতা তৈরি হয়।",
  },
  {
    number: 68,
    arabic: "الصَّمَدُ",
    transliterationBn: "আস-সামাদ",
    transliterationEn: "As-Samad",
    meaningBn: "অমুখাপেক্ষী ও পরম নির্ভরস্থল",
    meaningEn: "The Eternal / Self-Sufficient",
    explanationBn: "সবাই যাঁর মুখাপেক্ষী কিন্তু তিনি কারো মুখাপেক্ষী নন। সমস্ত সৃষ্টি যাঁর দ্বারে প্রার্থী।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-ইখলাস (১১২:২)",
    benefitBn: "সেহরির সময় ১২৫ বার পাঠ করলে মানুষের মুখাপেক্ষিতা থেকে মুক্তি পাওয়া যায়।",
  },
  {
    number: 69,
    arabic: "الْقَادِرُ",
    transliterationBn: "আল-ক্বাদির",
    transliterationEn: "Al-Qadir",
    meaningBn: "সর্বশক্তিমান",
    meaningEn: "The All-Capable",
    explanationBn: "যিনি যা ইচ্ছা তা করতে পূর্ণ সক্ষম। কোনো কিছুই তাঁকে অক্ষম করতে পারে না।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-আন'আম (৬:৬৫)",
    benefitBn: "২ রাকাত নফল নামাজের পর ১০০ বার পাঠ করলে কঠিন কাজ সহজ হয়।",
  },
  {
    number: 70,
    arabic: "الْمُقْتَدِرُ",
    transliterationBn: "আল-মুক্বতাদির",
    transliterationEn: "Al-Muqtadir",
    meaningBn: "প্রভাবশালী ও পূর্ণ নিয়ন্ত্রক",
    meaningEn: "The Dominant / Creator of All Power",
    explanationBn: "যাঁর ক্ষমতা সমস্ত সৃষ্টিকে নিয়ন্ত্রণ করে এবং কোনো প্রতিরোধ যাঁর সিদ্ধান্তকে আটকাতে পারে না।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-ক্বামার (৫৪:৪২)",
    benefitBn: "ঘুম থেকে উঠে নিয়মিত পাঠ করলে অন্তরে সত্যের আলো উদ্ভাসিত হয়।",
  },
  {
    number: 71,
    arabic: "الْمُقَدِّمُ",
    transliterationBn: "আল-মুকাদ্দিম",
    transliterationEn: "Al-Muqaddim",
    meaningBn: "অগ্রবর্তীকারী",
    meaningEn: "The Expediter / Promoter",
    explanationBn: "যিনি তাঁর প্রজ্ঞায় যাকে ইচ্ছা অগ্রবর্তী করেন এবং মর্যাদায় এগিয়ে দেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা ক্বাফ (৫০:২৮)",
    benefitBn: "যুদ্ধের ময়দানে কিংবা প্রতিযোগিতায় পাঠ করলে বিজয় ও সাহসিকতা লাভ হয়।",
  },
  {
    number: 72,
    arabic: "الْمُؤَخِّرُ",
    transliterationBn: "আল-মুআখ্খির",
    transliterationEn: "Al-Mu'akhkhir",
    meaningBn: "পশ্চাদবর্তীকারী",
    meaningEn: "The Delayer / Postponer",
    explanationBn: "যিনি তাঁর প্রজ্ঞায় যাকে ইচ্ছা পেছনে রাখেন এবং উপযুক্ত সময় পর্যন্ত বিলম্ব করেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা ইব্রাহীম (১৪:৪২)",
    benefitBn: "নিয়মিত ১০০ বার পাঠ করলে পাপের প্রবণতা দূর হয় ও আল্লাহর ভালোবাসা বৃদ্ধি পায়।",
  },
  {
    number: 73,
    arabic: "الْأَوَّلُ",
    transliterationBn: "আল-আউয়াল",
    transliterationEn: "Al-Awwal",
    meaningBn: "অনাদি / সর্বপ্রথম",
    meaningEn: "The First",
    explanationBn: "যাঁর কোনো সূচনা নেই। মহাবিশ্ব সৃষ্টির পূর্বেও তিনি চিরন্তনভাবে বিদ্যমান ছিলেন।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-হাদীদ (৫৭:৩)",
    benefitBn: "সন্তানহীন ব্যক্তি ৪০ দিন পর্যন্ত ১০০০ বার পাঠ করলে নেক সন্তান লাভ হয়।",
  },
  {
    number: 74,
    arabic: "الْآخِرُ",
    transliterationBn: "আল-আখির",
    transliterationEn: "Al-Akhir",
    meaningBn: "অনন্ত / সর্বশেষ",
    meaningEn: "The Last",
    explanationBn: "যাঁর কোনো সমাপ্তি নেই। সমস্ত সৃষ্টি ধ্বংস হয়ে যাওয়ার পরও তিনি চিরকাল থাকবেন।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-হাদীদ (৫৭:৩)",
    benefitBn: "প্রতিদিন ১০০০ বার পাঠ করলে অন্তর থেকে অনর্থক চিন্তা ও পাপের মোহ দূর হয়।",
  },
  {
    number: 75,
    arabic: "الظَّاهِرُ",
    transliterationBn: "আয-যাহির",
    transliterationEn: "Az-Zahir",
    meaningBn: "প্রকাশ্য ও সুস্পষ্ট",
    meaningEn: "The Manifest",
    explanationBn: "সৃষ্টিজগতের অজস্র নিদর্শন ও প্রমাণের মাধ্যমে যাঁর অস্তিত্ব সুস্পষ্ট ও দিবালোকের মতো প্রকাশ্য।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-হাদীদ (৫৭:৩)",
    benefitBn: "ইশরাকের নামাজের পর ৫০০ বার পাঠ করলে দৃষ্টিশক্তি ও অন্তরের আলো বাড়ে।",
  },
  {
    number: 76,
    arabic: "الْبَاطِنُ",
    transliterationBn: "আল-বাতিন",
    transliterationEn: "Al-Batin",
    meaningBn: "গুপ্ত ও অপ্রকাশ্য",
    meaningEn: "The Hidden",
    explanationBn: "যাঁকে চর্মচক্ষু দিয়ে দেখা যায় না কিন্তু তিনি সমস্ত সৃষ্টির অন্তস্থলে বিরাজমান ও সূক্ষ্মভাবে অবগত।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আল-হাদীদ (৫৭:৩)",
    benefitBn: "নিয়মিত পাঠ করলে অন্তরে আধ্যাত্মিক রহস্য উন্মোচিত হয়।",
  },
  {
    number: 77,
    arabic: "الْوَالِي",
    transliterationBn: "আল-ওয়ালী",
    transliterationEn: "Al-Waali",
    meaningBn: "একচ্ছত্র অভিভাবক ও শাসক",
    meaningEn: "The Governor / Ruler",
    explanationBn: "যিনি সমস্ত বিশ্বব্রহ্মাণ্ডের অভিভাবকত্ব ও সার্বিক ব্যবস্থাপনার একমাত্র নিয়ন্ত্রক।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আর-রাদ (১৩:১১)",
    benefitBn: "বিপদ-আপদে ঘরে বারবার পাঠ করলে নিরাপত্তা অর্জিত হয়।",
  },
  {
    number: 78,
    arabic: "الْمُتَعَالِي",
    transliterationBn: "আল-মুতা'আলী",
    transliterationEn: "Al-Muta'ali",
    meaningBn: "সর্বোচ্চ মর্যাদাসম্পন্ন",
    meaningEn: "The Supremely Exalted",
    explanationBn: "যিনি সমস্ত সৃষ্টির গুণাবলী, সীমাবদ্ধতা ও ধারণার ঊর্ধ্বে পরম সুউচ্চ।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আর-রাদ (১৩:৯)",
    benefitBn: "অধিক পরিমাণে পাঠ করলে পদোন্নতি ও মর্যাদা বৃদ্ধি পায়।",
  },
  {
    number: 79,
    arabic: "الْبَرُّ",
    transliterationBn: "আল-বার্র",
    transliterationEn: "Al-Barr",
    meaningBn: "পরম কল্যাণকারী ও পুণ্যময়",
    meaningEn: "The Source of All Goodness",
    explanationBn: "যিনি বান্দার প্রতি সর্বদা কল্যাণকামী এবং যাঁর কাছ থেকে কেবল মঙ্গলই নিঃসৃত হয়।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আত-তূর (৫২:২৮)",
    benefitBn: "সন্তানের ওপর হাত রেখে পাঠ করলে সন্তান সৎ ও অনুগত হয়।",
  },
  {
    number: 80,
    arabic: "التَّوَّابُ",
    transliterationBn: "আত-তাওয়াব",
    transliterationEn: "At-Tawwab",
    meaningBn: "তওবা কবুলকারী",
    meaningEn: "The Ever-Pardoning",
    explanationBn: "যিনি বারবার বান্দাকে অনুশোচনার তৌফিক দেন এবং আন্তরিক তওবা সাদরে গ্রহণ করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-বাক্বারাহ (২:৩৭)",
    benefitBn: "চাশতের নামাজের পর ৩৬০ বার পাঠ করলে সত্য তওবার তৌফিক হয়।",
  },
  {
    number: 81,
    arabic: "الْمُنْتَقِمُ",
    transliterationBn: "আল-মুনতাক্বিম",
    transliterationEn: "Al-Muntaqim",
    meaningBn: "প্রতিশোধ গ্রহণকারী",
    meaningEn: "The Avenger",
    explanationBn: "যিনি অবাধ্য জালিমদের ও অহংকারীদের বিরুদ্ধে উপযুক্ত ন্যায়সঙ্গত শাস্তিমূলক ব্যবস্থা গ্রহণ করেন।",
    category: "justice",
    categoryLabelBn: "ন্যায়বিচার ও ফায়সালা",
    quranReference: "সূরা আস-সাজদাহ (৩২:২২)",
    benefitBn: "অত্যাচারীর হাত থেকে আত্মরক্ষায় নিয়মিত পাঠ করলে আল্লাহ উপযুক্ত বিচার করেন।",
  },
  {
    number: 82,
    arabic: "العَفُوُّ",
    transliterationBn: "আল-আফুউ",
    transliterationEn: "Al-Afuww",
    meaningBn: "মার্জনাকারী",
    meaningEn: "The Supreme Pardoner",
    explanationBn: "যিনি কেবল ক্ষমাই করেন না, বরং পাপের সমস্ত দাগ ও অস্তিত্ব বান্দার আমলনামা থেকে সম্পূর্ণ মুছে দেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আন-নিসা (৪:৯৯)",
    benefitBn: "অধিক পরিমাণে 'আল্লাহুম্মা ইন্নাকা আফুউন' পাঠ করলে গুনাহ মাফ হয়।",
  },
  {
    number: 83,
    arabic: "الرَّؤُوفُ",
    transliterationBn: "আর-রউফ",
    transliterationEn: "Ar-Raoof",
    meaningBn: "অতিশয় স্নেহশীল ও সহানুভূতিশীল",
    meaningEn: "The Most Kind / Clement",
    explanationBn: "যাঁর বান্দার প্রতি স্নেহ ও মমতা সীমাহীন। তিনি কাউকে সাধ্যের অতিরিক্ত বোঝা চাপান না।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-বাক্বারাহ (২:২০৭)",
    benefitBn: "রাগ ও ক্রোধ দমনে ১০ বার দুরূদ সহ পাঠ করলে মন শান্ত হয়।",
  },
  {
    number: 84,
    arabic: "مَالِكُ الْمُلْكِ",
    transliterationBn: "মালিকুল মুলক",
    transliterationEn: "Malik-ul-Mulk",
    meaningBn: "মহাবিশ্বের চিরন্তন মালিক",
    meaningEn: "Owner of Absolute Sovereignty",
    explanationBn: "সমগ্র সৃষ্টিরাজ্যের চূড়ান্ত অধিপতি, যিনি যাকে ইচ্ছা রাজত্ব দেন এবং যার থেকে ইচ্ছা রাজত্ব কেড়ে নেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-ইমরান (৩:২৬)",
    benefitBn: "নিয়মিত পাঠ করলে আর্থিক স্বাধীনতা ও সম্মানজনক জীবন লাভ হয়।",
  },
  {
    number: 85,
    arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ",
    transliterationBn: "যুল জালালি ওয়াল ইকরাম",
    transliterationEn: "Dhul-Jalali wal-Ikram",
    meaningBn: "মহিমাময় ও মহানুভবতার অধিকারী",
    meaningEn: "Lord of Majesty and Generosity",
    explanationBn: "যিনি একইসাথে অপার মহত্ত্ব, প্রতাপ ও অফুরন্ত অনুগ্রহের পরম আধার।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আর-রহমান (৫৫:৭৮)",
    benefitBn: "দু'আয় 'ইয়া যাল জালালি ওয়াল ইকরাম' বলে চাইলে দু'আ দ্রুত কবুল হয়।",
  },
  {
    number: 86,
    arabic: "الْمُقْسِطُ",
    transliterationBn: "আল-মুক্বসিত",
    transliterationEn: "Al-Muqsit",
    meaningBn: "ন্যায়পরায়ণ ও ভারসাম্যকারী",
    meaningEn: "The Equitable",
    explanationBn: "যিনি সকল কাজের মধ্যে নিখুঁত সামঞ্জস্য ও পরিপূর্ণ ন্যায়বিচার প্রতিষ্ঠা করেন।",
    category: "justice",
    categoryLabelBn: "ন্যায়বিচার ও ফায়সালা",
    quranReference: "সূরা আল-ইমরান (৩:১৮)",
    benefitBn: "ওয়াসওয়াসা ও দ্বিধাদ্বন্দ্ব দূর করতে ১০০ বার পাঠ করা উপকারী।",
  },
  {
    number: 87,
    arabic: "الْجَامِعُ",
    transliterationBn: "আল-জামি'",
    transliterationEn: "Al-Jami",
    meaningBn: "একত্রকারী",
    meaningEn: "The Gatherer",
    explanationBn: "যিনি কিয়ামতের দিন সকল সৃষ্টিকে হিসাবের জন্য সমবেত করবেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-ইমরান (৩:৯)",
    benefitBn: "হারানো মানুষ বা স্বজনদের পুনর্মিলনের জন্য দু'আয় পাঠ করা উপকারী।",
  },
  {
    number: 88,
    arabic: "الْغَنِيُّ",
    transliterationBn: "আল-গনীয়্যু",
    transliterationEn: "Al-Ghaniyy",
    meaningBn: "পরম সম্পদশালী ও অমুখাপেক্ষী",
    meaningEn: "The Self-Sufficient / Rich",
    explanationBn: "যাঁর ভান্ডারের কোনো সীমা নেই এবং যিনি কারো কোনো কিছুর মুখাপেক্ষী নন।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আল-বাক্বারাহ (২:২৬৭)",
    benefitBn: "৭০ বার পাঠ করলে অন্তরের প্রাচুর্য ও সম্পদের বরকত অর্জিত হয়।",
  },
  {
    number: 89,
    arabic: "الْمُغْنِي",
    transliterationBn: "আল-মুগনী",
    transliterationEn: "Al-Mughni",
    meaningBn: "স্বয়ংসম্পূর্ণকারী ও অভাব দূরকারী",
    meaningEn: "The Enricher",
    explanationBn: "যিনি তাঁর বান্দাদের ধন-সম্পদ ও অন্তরের পরিতৃপ্তি দিয়ে অভাবমুক্ত করেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আন-নাজম (৫৩:৪৮)",
    benefitBn: "ফজরের পর ১০০০ বার পাঠ করলে অভাব দূর হয় ও সচ্ছলতা আসে।",
  },
  {
    number: 90,
    arabic: "الْمَانِعُ",
    transliterationBn: "আল-মানি'",
    transliterationEn: "Al-Mani",
    meaningBn: "নিষেধকারী ও প্রতিরোধক",
    meaningEn: "The Withholder / Preventer",
    explanationBn: "যিনি তাঁর প্রজ্ঞায় যা ক্ষতিকর তা বান্দার কাছে পৌঁছাতে বাধা দেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "হাদিস শরীফ (তিরমিযী)",
    benefitBn: "পারিবারিক অশান্তি ও অপচয় বন্ধে ঘুমানোর সময় ২০ বার পাঠ করা উপকারী।",
  },
  {
    number: 91,
    arabic: "الضَّارُّ",
    transliterationBn: "আদ-দার্র",
    transliterationEn: "Ad-Darr",
    meaningBn: "ক্ষতি পৌঁছাতে সক্ষম",
    meaningEn: "The Distressor / Creator of Harm",
    explanationBn: "যাঁর অনুমতি ছাড়া কোনো ক্ষতি বান্দাকে স্পর্শ করতে পারে না। তিনি অবাধ্যদের সতর্ককারী।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-আন'আম (৬:১৭)",
    benefitBn: "জুমার রাতে ১০০ বার পাঠ করলে আত্মিক শান্তি ও বিপদ থেকে নিরাপত্তা লাভ হয়।",
  },
  {
    number: 92,
    arabic: "النَّافِعُ",
    transliterationBn: "আন-নাফি'",
    transliterationEn: "An-Nafi",
    meaningBn: "উপকারকারী ও কল্যাণদাতা",
    meaningEn: "The Propitious / Benefactor",
    explanationBn: "যিনি একমাত্র কল্যাণ ও উপকারের সৃষ্টিকর্তা। কোনো ভালো জিনিস যাঁর অনুমতি ব্যতীত ঘটে না।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-আন'আম (৬:১৭)",
    benefitBn: "যেকোনো কাজ শুরুর আগে ৪১ বার পাঠ করলে তাতে প্রচুর উপকার লাভ হয়।",
  },
  {
    number: 93,
    arabic: "النُّورُ",
    transliterationBn: "আন-নূর",
    transliterationEn: "An-Noor",
    meaningBn: "পরম জ্যোতি ও আলোকবর্তিকা",
    meaningEn: "The Light",
    explanationBn: "যিনি সমগ্র আসমান ও যমীনের আলোকবর্তিকা এবং যাঁর হেদায়েতের নূর অন্তরকে আলোকিত করে।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আন-নূর (২৪:৩৫)",
    benefitBn: "সূরা নূর তিলাওয়াতের পর ১০০৭ বার পাঠ করলে অন্তর দিব্যজ্ঞানে উদ্ভাসিত হয়।",
  },
  {
    number: 94,
    arabic: "الْهَادِي",
    transliterationBn: "আল-হাদী",
    transliterationEn: "Al-Hadi",
    meaningBn: "সঠিক পথপ্রদর্শক",
    meaningEn: "The Guide",
    explanationBn: "যিনি বিভ্রান্ত হৃদয়কে সত্য ও ন্যায়ের সরল সঠিক পথ (সিরাতাল মুস্তাকিম) প্রদর্শন করেন।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আল-হাজ্জ (২২:৫৪)",
    benefitBn: "দুই হাত তুলে আকাশে তাকিয়ে অধিক পরিমাণে পাঠ করলে হেদায়েত ও সুপথ লাভ হয়।",
  },
  {
    number: 95,
    arabic: "الْبَدِيعُ",
    transliterationBn: "আল-বাদী'",
    transliterationEn: "Al-Badi",
    meaningBn: "অনুপম রূপকার ও নজিরবিহীন সৃষ্টিকর্তা",
    meaningEn: "The Incomparable Originator",
    explanationBn: "যিনি কোনো পূর্ব দৃষ্টান্ত ও কাঁচামাল ব্যতীত অনুপম সৌন্দর্যে মহাবিশ্ব সৃষ্টি করেছেন।",
    category: "creation",
    categoryLabelBn: "সৃষ্টি ও প্রতিপালন",
    quranReference: "সূরা আল-বাক্বারাহ (২:১১৭)",
    benefitBn: "যেকোনো কঠিন জটিলতায় 'ইয়া বাদী' আস-সামাওয়াতি ওয়াল আরদ' ৭০ বার পাঠ করলে সমাধান মেলে।",
  },
  {
    number: 96,
    arabic: "الْبَاقِي",
    transliterationBn: "আল-বাক্বী",
    transliterationEn: "Al-Baqi",
    meaningBn: "চিরস্থায়ী ও অবিনশ্বর",
    meaningEn: "The Everlasting",
    explanationBn: "সকল সৃষ্টির বিনাশের পরও যাঁর অস্তিত্ব চিরন্তনভাবে অক্ষয় ও অটুট থাকবে।",
    category: "praise",
    categoryLabelBn: "পবিত্রতা ও প্রশংসা",
    quranReference: "সূরা আর-রহমান (৫৫:২৭)",
    benefitBn: "সূর্যোদয়ের পূর্বে ১০০ বার পাঠ করলে সকল প্রকার ক্ষতি থেকে আল্লাহ হেফাজত করেন।",
  },
  {
    number: 97,
    arabic: "الْوَارِثُ",
    transliterationBn: "আল-ওয়ারিছ",
    transliterationEn: "Al-Warith",
    meaningBn: "একমাত্র পরম উত্তরাধিকারী",
    meaningEn: "The Supreme Inheritor",
    explanationBn: "সকল সৃষ্টি ও তাদের সম্পদের বিনাশের পর যিনি সবকিছুর একমাত্র প্রকৃত মালিক হিসেবে অবশিষ্ট থাকবেন।",
    category: "power",
    categoryLabelBn: "ক্ষমতা ও আধিপত্য",
    quranReference: "সূরা আল-হিজর (১৫:২৩)",
    benefitBn: "সূর্যোদয়ের সময় ১০০ বার পাঠ করলে জীবন ও সম্পদে দীর্ঘস্থায়ী বরকত হয়।",
  },
  {
    number: 98,
    arabic: "الرَّشِيدُ",
    transliterationBn: "আর-রাশীদ",
    transliterationEn: "Ar-Rasheed",
    meaningBn: "সঠিক পরিচালনাকারী ও সুপরামর্শক",
    meaningEn: "The Infallible Guide",
    explanationBn: "যাঁর সকল পরিকল্পনা নির্ভুল এবং যিনি তাঁর সৃষ্টিকে সর্বোত্তম পরিণতির দিকে পরিচালিত করেন।",
    category: "knowledge",
    categoryLabelBn: "জ্ঞান ও প্রজ্ঞা",
    quranReference: "সূরা আল-কাহফ (১৮:১০)",
    benefitBn: "মাগরিব ও এশার মাঝে ১০০০ বার পাঠ করলে কাজের জটিলতা দূর হয়ে সঠিক পথ পাওয়া যায়।",
  },
  {
    number: 99,
    arabic: "الصَّبُورُ",
    transliterationBn: "আস-সবূর",
    transliterationEn: "As-Saboor",
    meaningBn: "পরম ধৈর্যশীল",
    meaningEn: "The Most Patient",
    explanationBn: "যিনি বান্দার অন্যায় ও অবাধ্যতায় কখনোই ধৈর্যহারা হন না এবং ত্বরিত শাস্তি না দিয়ে অবকাশ দেন।",
    category: "mercy",
    categoryLabelBn: "দয়া ও করুণা",
    quranReference: "সূরা আল-বাক্বারাহ (২:১৫৩)",
    benefitBn: "সূর্যোদয়ের আগে ৩০০০ বার পাঠ করলে বিপদ-আপদ ও শত্রুতা থেকে পরম সুরক্ষা লাভ হয়।",
  },
]
