export interface DuaItem {
  id: string
  titleBn: string
  titleEn: string
  category: "rabbana" | "morning-evening" | "forgiveness" | "anxiety" | "healing" | "rizq" | "family" | "daily"
  categoryLabelBn: string
  arabic: string
  transliterationBn: string
  transliterationEn: string
  translationBn: string
  translationEn: string
  reference: string
  benefitBn: string
  recommendedCount?: number
}

export const DUA_CATEGORIES = [
  { id: "all", labelBn: "সকল দু'আ", icon: "✨" },
  { id: "rabbana", labelBn: "৪০টি রাব্বানা দু'আ", icon: "📖" },
  { id: "morning-evening", labelBn: "সকাল-সন্ধ্যার আযকার", icon: "🌅" },
  { id: "forgiveness", labelBn: "ক্ষমা ও তওবা", icon: "🤲" },
  { id: "anxiety", labelBn: "বিপদ ও দুশ্চিন্তা দূরীকরণ", icon: "🛡️" },
  { id: "healing", labelBn: "রোগমুক্তি ও শেফা", icon: "🌿" },
  { id: "rizq", labelBn: "রিজিক বৃদ্ধি ও ঋণমুক্তি", icon: "💎" },
  { id: "family", labelBn: "পিতা-মাতা ও পরিবার", icon: "🏡" },
  { id: "daily", labelBn: "প্রাত্যহিক জীবনের দু'আ", icon: "☀️" },
]

export const AUTHENTIC_DUAS_COLLECTION: DuaItem[] = [
  // 40 Rabbana Duas
  {
    id: "rabbana-1",
    titleBn: "রাব্বানা দু'আ ১ — আমল কবুল হওয়ার দু'আ",
    titleEn: "Rabbana Dua 1 - Acceptance of Good Deeds",
    category: "rabbana",
    categoryLabelBn: "৪০টি রাব্বানা দু'আ",
    arabic: "رَبَّنَا تَقَبَّلْ مِنَّا ۖ إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ",
    transliterationBn: "রাব্বানা তাক্বাব্বাল মিন্না, ইন্নাকা আনতাস সামী'উল 'আলীম।",
    transliterationEn: "Rabbana taqabbal minna, innaka Antas-Samee'ul-Aleem.",
    translationBn: "হে আমাদের প্রতিপালক! আমাদের পক্ষ থেকে (এই আমল) কবুল করে নিন। নিশ্চয়ই আপনি সর্বশ্রোতা, সর্বজ্ঞাত।",
    translationEn: "Our Lord, accept this from us. Indeed You are the All-Hearing, the All-Knowing.",
    reference: "সূরা আল-বাক্বারাহ (২:১২৭) — ইব্রাহীম ও ইসমাঈল (আঃ) এর দু'আ",
    benefitBn: "যেকোনো নেক আমল, দান-সদকা, নামাজ ও রোজা শেষে কবুল হওয়ার জন্য অত্যন্ত শ্রেষ্ঠ দু'আ।",
  },
  {
    id: "rabbana-2",
    titleBn: "রাব্বানা দু'আ ২ — খাঁটি মুসলিম ও তওবা কবুল হওয়ার দু'আ",
    titleEn: "Rabbana Dua 2 - Devotion & Repentance",
    category: "rabbana",
    categoryLabelBn: "৪০টি রাব্বানা দু'আ",
    arabic: "رَبَّنَا وَاجْعَلْنَا مُسْلِمَيْنِ لَكَ وَمِن ذُرِّيَّتِنَا أُمَّةً مُّسْلِمَةً لَّكَ وَأَرِنَا مَنَاسِكَنَا وَتُبْ عَلَيْنَا ۖ إِنَّكَ أَنتَ التَّوَّابُ الرَّحِيمُ",
    transliterationBn: "রাব্বানা ওয়াজ'আলনা মুসলিমাইনি লাকা ওয়া মিন যুররিয়্যাতিনা উম্মাতাম মুসলি মাতাল লাকা, ওয়া আরিনা মানাসিকানা ওয়া তুব 'আলাইনা, ইন্নাকা আনতাত তাওয়াবুর রাহীম।",
    transliterationEn: "Rabbana waj'alna muslimayni laka wa min dhurriyyatina ummatan muslimatan laka wa arina manasikana wa tub 'alayna, innaka Antat-Tawwabur-Raheem.",
    translationBn: "হে আমাদের পালনকর্তা! আমাদের উভয়কে আপনার অনুগত করুন এবং আমাদের বংশধরদের থেকেও আপনার এক অনুগত জাতি সৃষ্টি করুন। আমাদের ইবাদতের পদ্ধতি দেখিয়ে দিন এবং আমাদের তওবা কবুল করুন। নিশ্চয়ই আপনি তওবা কবুলকারী, পরম দয়ালু।",
    translationEn: "Our Lord, make us devoted to You and from our descendants a nation devoted to You, and show us our rituals and accept our repentance.",
    reference: "সূরা আল-বাক্বারাহ (২:১২৮)",
    benefitBn: "পরিবার ও সন্তানদের দ্বীনের ওপর অবিচল রাখা এবং তওবা কবুলিয়াতের অনুপম প্রার্থনা।",
  },
  {
    id: "rabbana-3",
    titleBn: "রাব্বানা দু'আ ৩ — ইহকাল ও পরকালের সর্বাঙ্গীন কল্যাণ",
    titleEn: "Rabbana Dua 3 - Good in this World and the Hereafter",
    category: "rabbana",
    categoryLabelBn: "৪০টি রাব্বানা দু'আ",
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    transliterationBn: "রাব্বানা আতিনা ফিদ দুনইয়া হাসানাতাঁও ওয়া ফিল আখিরাতি হাসানাতাঁও ওয়া ক্বিনা 'আযাবান নার।",
    transliterationEn: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhaban-nar.",
    translationBn: "হে আমাদের প্রতিপালক! আমাদের দুনিয়াতেও কল্যাণ দান করুন এবং আখিরাতেও কল্যাণ দান করুন, আর আমাদেরকে জাহান্নামের আগুন থেকে রক্ষা করুন।",
    translationEn: "Our Lord, give us in this world that which is good and in the Hereafter that which is good and protect us from the punishment of the Fire.",
    reference: "সূরা আল-বাক্বারাহ (২:২০১) — রাসূলুল্লাহ ﷺ এর সর্বাধিক পঠিত দু'আ",
    benefitBn: "জীবনের প্রতিটি পদক্ষেপে, তাওয়াফের সময় এবং ফরজ নামাজের পর এই দু'আ পাঠ করা সুন্নাত।",
  },
  {
    id: "rabbana-4",
    titleBn: "রাব্বানা দু'আ ৪ — ঈমানের দৃঢ়তা ও কাফেরদের বিরুদ্ধে সাহায্য",
    titleEn: "Rabbana Dua 4 - Patience and Victory over Adversaries",
    category: "rabbana",
    categoryLabelBn: "৪০টি রাব্বানা দু'আ",
    arabic: "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
    transliterationBn: "রাব্বানা আফরিগ 'আলাইনা সবরাঁও ওয়া ছাব্বিত আক্বদামানা ওয়ানসুরনা 'আলাল ক্বাওমিল কাফিরীন।",
    transliterationEn: "Rabbana afrigh 'alayna sabran wa thabbit aqdamana wansurna 'alal-qawmil-kafireen.",
    translationBn: "হে আমাদের প্রতিপালক! আমাদের ওপর ধৈর্য ঢেলে দিন, আমাদের পা দৃঢ় রাখুন এবং সত্য অস্বীকারকারী সম্প্রদায়ের বিরুদ্ধে আমাদের সাহায্য করুন।",
    translationEn: "Our Lord, pour upon us patience and plant firmly our feet and give us victory over the disbelieving people.",
    reference: "সূরা আল-বাক্বারাহ (২:২৫০) — তালুত ও দাউদ (আঃ) এর সেনাদলের দু'আ",
    benefitBn: "জীবনের কঠিন পরীক্ষায় ধৈর্য ও অবিচলতা অর্জনে অপরিসীম শক্তিশালী দু'আ।",
  },
  {
    id: "rabbana-5",
    titleBn: "রাব্বানা দু'আ ৫ — ভুলত্রুটি ক্ষমা ও ক্ষমার আবেদন",
    titleEn: "Rabbana Dua 5 - Forgiveness for Mistakes and Forgetfulness",
    category: "rabbana",
    categoryLabelBn: "৪০টি রাব্বানা দু'আ",
    arabic: "رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ۖ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ۚ أَنتَ مَوْلَانَا فَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
    transliterationBn: "রাব্বানা লা তুআখিযনা ইন নাসীনা আও আখতানা, রাব্বানা ওয়ালা তাহমিল 'আলাইনা ইসরান কামা হামালতাহু 'আলাল্লাযীনা মিন ক্বাবলিনা, রাব্বানা ওয়ালা তুহাম্মিলনা মা লা তাক্বাতা লানা বিহ, ওয়া'ফু 'আন্না ওয়াগফির লানা ওয়ারহামনা, আনতা মাওলresource ওয়ানসুরনা 'আলাল ক্বাওমিল কাফিরীন।",
    transliterationEn: "Rabbana la tu'akhidhna in naseena aw akhta'na, Rabbana wa la tahmil 'alayna isran kama hamaltahu 'alalladheena min qablina...",
    translationBn: "হে আমাদের প্রতিপালক! যদি আমরা ভুলে যাই কিংবা ভুল করি, তবে আমাদের পাকড়াও করবেন না। হে আমাদের পালনকর্তা! আমাদের ওপর এমন ভারী বোঝা চাপাবেন না যেমন পূর্ববর্তীদের ওপর চাপিয়েছিলেন। হে আমাদের রব! যার সামর্থ্য আমাদের নেই, তা আমাদের ওপর চাপাবেন না। আমাদের ক্ষমা করুন, আমাদের মার্জনা করুন এবং আমাদের প্রতি দয়া করুন।",
    translationEn: "Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us...",
    reference: "সূরা আল-বাক্বারাহ (২:২৮৬) — সূরা বাক্বারাহর শেষ আয়াত",
    benefitBn: "রাতে এই আয়াতদ্বয় পাঠ করলে রাতের সমস্ত অনিষ্ট থেকে সুরক্ষার জন্য যথেষ্ট হয় (বুখারী)।",
  },
  {
    id: "rabbana-6",
    titleBn: "রাব্বানা দু'আ ৬ — হেদায়েতের পর অন্তরের বক্রতা থেকে বাঁচার দু'আ",
    titleEn: "Rabbana Dua 6 - Steadfastness in Guidance",
    category: "rabbana",
    categoryLabelBn: "৪০টি রাব্বানা দু'আ",
    arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ الْوَهَّابُ",
    transliterationBn: "রাব্বানা লা তুযিগ ক্বুলূবানা বা'দা ইয হাদাইতানা ওয়াহাব লানা মিল্লাদুনকা রাহমাহ, ইন্নাকা আনতাল ওয়াহ্হাব।",
    transliterationEn: "Rabbana la tuzigh quloobana ba'da idh hadaytana wa hab lana min ladunka rahmah, innaka Antal-Wahhab.",
    translationBn: "হে আমাদের প্রতিপালক! সরল পথ দেখানোর পর আমাদের অন্তরকে সত্যচ্যুত করবেন না এবং আপনার নিকট থেকে আমাদের বিশেষ রহমত দান করুন। নিশ্চয়ই আপনি পরম দাতা।",
    translationEn: "Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.",
    reference: "সূরা আল-ইমরান (৩:৮)",
    benefitBn: "ঈমানের ওপর আমৃত্যু অবিচল থাকার জন্য এই দু'আ নিয়মিত পাঠ করা কর্তব্য।",
  },
  {
    id: "rabbana-7",
    titleBn: "রাব্বানা দু'আ ৭ — গুনাহ মাফ ও জাহান্নাম থেকে মুক্তি",
    titleEn: "Rabbana Dua 7 - Forgiveness and Salvation from Fire",
    category: "rabbana",
    categoryLabelBn: "৪০টি রাব্বানা দু'আ",
    arabic: "رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ",
    transliterationBn: "রাব্বানা ইন্নানা আমান্না ফাগফির লানা যুনূবানা ওয়া ক্বিনা 'আযাবান নার।",
    transliterationEn: "Rabbana innana amanna faghfir lana dhunoobana wa qina 'adhaban-nar.",
    translationBn: "হে আমাদের প্রতিপালক! আমরা তো আপনার প্রতি ঈমান এনেছি, অতএব আমাদের গুনাহসমূহ ক্ষমা করে দিন এবং আমাদের জাহান্নামের আযাব থেকে রক্ষা করুন।",
    translationEn: "Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire.",
    reference: "সূরা আল-ইমরান (৩:১৬)",
    benefitBn: "তাহাজ্জুদ ও সেহরির সময়ে ক্ষমার জন্য অত্যন্ত উপযোগী কুরআনী দু'আ।",
  },
  {
    id: "rabbana-8",
    titleBn: "রাব্বানা দু'আ ৮ — পিতা-মাতা ও সমস্ত মুমিনের জন্য ক্ষমা প্রার্থনা",
    titleEn: "Rabbana Dua 8 - Forgiveness for Parents and Believers",
    category: "rabbana",
    categoryLabelBn: "৪০টি রাব্বানা দু'আ",
    arabic: "رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ",
    transliterationBn: "রাব্বানাগফির লী ওয়ালি ওয়ালিদাইয়্যা ওয়া লিল-মু'মিনীনা ইয়াওমা ইয়াক্বূমুল হিসাব।",
    transliterationEn: "Rabbana-ghfir lee wa liwalidayya wa lil-mu'mineena yawma yaqoomul-hisaab.",
    translationBn: "হে আমাদের প্রতিপালক! আমাকে, আমার পিতা-মাতাকে এবং সমস্ত মুমিনদের ক্ষমা করে দিন—যেদিন হিসাব কায়েম হবে।",
    translationEn: "Our Lord, forgive me and my parents and the believers the Day the account is established.",
    reference: "সূরা ইব্রাহীম (১৪:৪১) — ইব্রাহীম (আঃ) এর বিশ্বখ্যাত দু'আ",
    benefitBn: "নামাজের শেষ বৈঠকে তাশাহহুদ ও দুরূদের পর এবং প্রত্যহ পিতা-মাতার জন্য পাঠ্য।",
  },
  {
    id: "rabbana-9",
    titleBn: "রাব্বানা দু'আ ৯ — নেককার স্ত্রী ও নয়নপ্রীতি সন্তান লাভের দু'আ",
    titleEn: "Rabbana Dua 9 - Righteous Family and Children",
    category: "rabbana",
    categoryLabelBn: "৪০টি রাব্বানা দু'আ",
    arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    transliterationBn: "রাব্বানা হাব লানা মিন আযওয়াজিনা ওয়া যুররিয়্যাতিনা ক্বুররাতা আ'ইয়ুনিঁও ওয়াজ'আলনা লিলমুত্তাক্বীনা ইমামা।",
    transliterationEn: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqeena imama.",
    translationBn: "হে আমাদের প্রতিপালক! আমাদের স্ত্রী ও সন্তানদের আমাদের জন্য চোখের শীতলতা স্বরূপ বানিয়ে দিন এবং আমাদের মুত্তাকীদের নেতা বানান।",
    translationEn: "Our Lord, grant us from among our wives and offspring comfort to our eyes and make us an example for the righteous.",
    reference: "সূরা আল-ফুরক্বান (২৫:৭৪) — রাহমানের খাঁটি বান্দাদের গুণাবলী",
    benefitBn: "দাম্পত্য জীবনে সুখ-শান্তি এবং সন্তানদের সৎ ও আদর্শ হিসেবে গড়ে তুলতে পঠিতব্য।",
  },
  {
    id: "rabbana-10",
    titleBn: "রাব্বানা দু'আ ১০ — অন্তরে ঈমানদারদের প্রতি হিংসামুক্ত থাকার দু'আ",
    titleEn: "Rabbana Dua 10 - Purity of Heart Towards Believers",
    category: "rabbana",
    categoryLabelBn: "৪০টি রাব্বানা দু'আ",
    arabic: "رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ وَلَا تَجْعَلْ فِي قُلُوبِنَا غِلًّا لِّلَّذِينَ آمَنُوا رَبَّنَا إِنَّكَ رَءُوفٌ رَّحِيمٌ",
    transliterationBn: "রাব্বানাগফির লানা ওয়ালি-ইখওয়ানিনাল্লাযীনা সাবাক্বূনা বিল-ঈমানি ওয়ালা তাজ'আল ফী ক্বুলূবিনা গিল্লাল লিল্লাযীনা আমানূ, রাব্বানা ইন্নাকা রাউফুর রাহীম।",
    transliterationEn: "Rabbana-ghfir lana wa li-ikhwaninalladheena sabaqoona bil-eeman...",
    translationBn: "হে আমাদের প্রতিপালক! আমাদের এবং আমাদের পূর্ববর্তী ঈমানদার ভাইদের ক্ষমা করুন। আর যারা ঈমান এনেছে তাদের বিরুদ্ধে আমাদের অন্তরে কোনো হিংসা-বিদ্বেষ রাখবেন না। হে আমাদের রব! নিশ্চয়ই আপনি অতিশয় স্নেহশীল, পরম দয়ালু।",
    translationEn: "Our Lord, forgive us and our brothers who preceded us in faith and put not in our hearts any resentment toward those who have believed.",
    reference: "সূরা আল-হাশর (৫৯:১০)",
    benefitBn: "অন্তরের হিংসা, অহংকার ও শত্রুতা দূর করে পারস্পরিক ভ্রাতৃত্ব ও ভালোবাসা বৃদ্ধি করে।",
  },

  // Morning & Evening Adhkar
  {
    id: "adhkar-morning-1",
    titleBn: "সকাল-সন্ধ্যার প্রধান যিকির — আয়াতুল কুরসী",
    titleEn: "Morning/Evening - Ayat al-Kursi",
    category: "morning-evening",
    categoryLabelBn: "সকাল-সন্ধ্যার আযকার",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ",
    transliterationBn: "আল্লাহু লা ইলাহা ইল্লা হুওয়াল হাইয়্যুল ক্বাইয়্যূম...",
    transliterationEn: "Allahu la ilaha illa Huwa, Al-Hayyul-Qayyoom...",
    translationBn: "আল্লাহ, তিনি ছাড়া কোনো সত্য উপাস্য নেই। তিনি চিরঞ্জীব, সর্বসত্তার ধারক। তন্দ্রা বা নিদ্রা তাঁকে স্পর্শ করে না। আসমান ও যমীনে যা কিছু আছে সব তাঁরই...",
    translationEn: "Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence...",
    reference: "সূরা আল-বাক্বারাহ (২:২৫৫) — সহীহ বুখারী ও নাসায়ী",
    benefitBn: "সকালে পাঠ করলে সন্ধ্যা পর্যন্ত এবং সন্ধ্যায় পাঠ করলে সকাল পর্যন্ত শয়তান ও সমস্ত অনিষ্ট থেকে নিরাপদ থাকা যায়।",
    recommendedCount: 1,
  },
  {
    id: "adhkar-morning-2",
    titleBn: "সকাল-সন্ধ্যার অনিষ্ট থেকে বাঁচার দু'আ (৩ বার)",
    titleEn: "Protection from Harm in Morning/Evening",
    category: "morning-evening",
    categoryLabelBn: "সকাল-সন্ধ্যার আযকার",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transliterationBn: "বিসমিল্লাহিল্লাযী লা ইয়াদুররু মা'আসমিহী শাইউন ফিল আরদ্বি ওয়ালা ফিস সামা-ই, ওয়া হুওয়াস সামী'উল 'আলীম।",
    transliterationEn: "Bismillahilladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa Huwas-Samee'ul-Aleem.",
    translationBn: "আল্লাহর নামে (দিন শুরু/শেষ করছি), যাঁর নামের সাথে আসমান ও যমীনের কোনো কিছুই কোনো ক্ষতিসাধন করতে পারে না; আর তিনি সর্বশ্রোতা, সর্বজ্ঞাত।",
    translationEn: "In the name of Allah, with whose name nothing can cause harm in the earth nor in the heaven, and He is the All-Hearing, the All-Knowing.",
    reference: "সুনান আবু দাউদ (৫০৮৮), জামে তিরমিযী (৩৩৮৮) — হাসান সহীহ",
    benefitBn: "সকাল-সন্ধ্যায় ৩ বার পাঠ করলে কোনো বিষাক্ত প্রাণী, জাদু বা হঠাৎ বিপদ ক্ষতি করতে পারে না।",
    recommendedCount: 3,
  },
  {
    id: "adhkar-morning-3",
    titleBn: "আল্লাহর পূর্ণাঙ্গ সন্তুষ্টি অর্জনের দু'আ (৩ বার)",
    titleEn: "Pleasure of Allah in Morning/Evening",
    category: "morning-evening",
    categoryLabelBn: "সকাল-সন্ধ্যার আযকার",
    arabic: "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا",
    transliterationBn: "রাদীতু বিল্লাহি রাব্বাঁও, ওয়া বিল ইসলামি দীনাঁও, ওয়া বি-মুহাম্মাদিন সাল্লাল্লাহু 'আলাইহি ওয়াসাল্লামা নাবিয়্যা।",
    transliterationEn: "Radeetu billahi Rabban, wa bil-Islami deenan, wa bi-Muhammadin sallallahu 'alayhi wa sallama Nabiyya.",
    translationBn: "আমি আল্লাহকে প্রতিপালক হিসেবে, ইসলামকে দ্বীন হিসেবে এবং মুহাম্মাদ ﷺ-কে নবী হিসেবে পেয়ে সন্তুষ্ট চিত্তে গ্রহণ করেছি।",
    translationEn: "I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad (peace be upon him) as my Prophet.",
    reference: "সুনান আবু দাউদ (১৫২৯), জামে তিরমিযী (৩৩৮৯)",
    benefitBn: "যে ব্যক্তি সকাল-সন্ধ্যায় ৩ বার পাঠ করবে, কিয়ামতের দিন তাকে সন্তুষ্ট করা আল্লাহর দায়িত্ব হয়ে যায় (তিরমিযী)।",
    recommendedCount: 3,
  },

  // Forgiveness & Tawbah
  {
    id: "forgiveness-sayyidul-istighfar",
    titleBn: "সাইয়্যিদুল ইস্তিগফার (তওবার সর্বশ্রেষ্ঠ দু'আ)",
    titleEn: "Sayyidul Istighfar - Master of Forgiveness",
    category: "forgiveness",
    categoryLabelBn: "ক্ষমা ও তওবা",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    transliterationBn: "আল্লাহুম্মা আনতা রাব্বী লা ইলাহা ইল্লা আনতা, খালাক্বতানী ওয়া আনা 'আবদুকা, ওয়া আনা 'আলা 'আহদিকা ওয়া ওয়া'দিকা মাসতাত্বা'তু, আ'ঊযু বিকা মিন শাররি মা সানা'তু, আবূউ লাকা বিনি'মাতিকা 'আলাইয়্যা, ওয়া আবূউ লাকা বিযাম্বী ফাগফির লী, ফাইন্নাহূ লা ইয়াগফিরুয যুনূবা ইল্লা আনতা।",
    transliterationEn: "Allahumma Anta Rabbi la ilaha illa Anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastata'tu...",
    translationBn: "হে আল্লাহ! আপনিই আমার প্রতিপালক, আপনি ব্যতীত কোনো উপাস্য নেই। আপনি আমাকে সৃষ্টি করেছেন এবং আমি আপনারই বান্দা। আমি আমার সাধ্যানুযায়ী আপনার সাথে কৃত অঙ্গীকার ও প্রতিশ্রুতির ওপর অবিচল আছি। আমি আমার কৃতকর্মের অনিষ্ট থেকে আপনার আশ্রয় চাই। আমার ওপর আপনার যে নিয়ামত রয়েছে তা স্বীকার করছি এবং আমার গুনাহও স্বীকার করছি। অতএব আমাকে ক্ষমা করে দিন; কেননা আপনি ছাড়া আর কেউ গুনাহ ক্ষমা করতে পারে না।",
    translationEn: "O Allah, You are my Lord, there is no deity except You. You have created me and I am Your servant...",
    reference: "সহীহ বুখারী (৬৩০৬)",
    benefitBn: "যে ব্যক্তি দিনে দৃঢ় বিশ্বাসের সাথে পাঠ করে সন্ধ্যার আগে মারা যাবে সে জান্নাতী হবে, এবং রাতে পাঠ করে সকালের আগে মারা গেলেও সে জান্নাতী হবে।",
    recommendedCount: 1,
  },
  {
    id: "forgiveness-yunus",
    titleBn: "ইউনুস (আঃ) এর দোয়া ইউনুস — সংকট মুক্তির দু'আ",
    titleEn: "Dua Yunus - Relief in Severe Calamity",
    category: "anxiety",
    categoryLabelBn: "বিপদ ও দুশ্চিন্তা দূরীকরণ",
    arabic: "لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
    transliterationBn: "লা ইলাহা ইল্লা আনতা সুবহানাকা ইন্নী কুনতু মিনায যালিমীন।",
    transliterationEn: "La ilaha illa Anta subhanaka innee kuntu minaz-zalimeen.",
    translationBn: "আপনি ব্যতীত কোনো সত্য উপাস্য নেই; আপনি পরম পবিত্র ও মহিমান্বিত। নিশ্চয়ই আমি অত্যাচারীদের অন্তর্ভুক্ত হয়ে গেছি।",
    translationEn: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.",
    reference: "সূরা আল-আম্বিয়া (২১:৮৭) — জামে তিরমিযী (৩৫০৫)",
    benefitBn: "রাসূলুল্লাহ ﷺ বলেছেন: যেকোনো মুসলিম কোনো সংকটে এই দু'আ পাঠ করে আল্লাহর কাছে চাইলে অবশ্যই তার দু'আ কবুল হয়।",
    recommendedCount: 100,
  },

  // Anxiety, Grief & Distress
  {
    id: "anxiety-distress-1",
    titleBn: "অস্থিরতা, দুশ্চিন্তা ও ঋণগ্রস্ততা থেকে মুক্তির দু'আ",
    titleEn: "Protection from Anxiety, Sorrow, and Debt",
    category: "anxiety",
    categoryLabelBn: "বিপদ ও দুশ্চিন্তা দূরীকরণ",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ، وَغَلَبَةِ الرِّجَالِ",
    transliterationBn: "আল্লাহুম্মা ইন্নী আ'ঊযু বিকা মিনাল হাম্মি ওয়াল হাযানি, ওয়াল 'আজযি ওয়াল কাসালি, ওয়াল বুখলি ওয়াল জুবনি, ওয়া দ্বালা'ইদ দাইনি, ওয়া গালাবাতির রিজাল।",
    transliterationEn: "Allahumma innee a'oodhu bika minal-hammi wal-hazani, wal-'ajzi wal-kasali, wal-bukhli wal-jubni, wa dala'id-dayni, wa ghalabatir-rijal.",
    translationBn: "হে আল্লাহ! আমি আপনার আশ্রয় চাই দুশ্চিন্তা ও বিষাদ থেকে, অক্ষমতা ও অলসতা থেকে, কৃপণতা ও কাপুরুষতা থেকে, ঋণের অসহনীয় চাপ থেকে এবং মানুষের অন্যায় আধিপত্য থেকে।",
    translationEn: "O Allah, I seek refuge in You from grief and sadness, from weakness and laziness, from miserliness and cowardice, from being overcome by debt and overpowered by men.",
    reference: "সহীহ বুখারী (২৮৯৩)",
    benefitBn: "সকাল-সন্ধ্যায় নিয়মিত পাঠ করলে মানসিক চাপ, বিষণ্ণতা ও আর্থিক দৈন্য দূর হয়।",
  },

  // Healing & Shifa
  {
    id: "healing-shifa-1",
    titleBn: "অসুস্থ ব্যক্তির রোগমুক্তি ও আরোগ্য লাভের দু'আ",
    titleEn: "Dua for Shifa and Healing the Sick",
    category: "healing",
    categoryLabelBn: "রোগমুক্তি ও শেফা",
    arabic: "اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَاسَ، اشْفِهِ وَأَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا",
    transliterationBn: "আল্লাহুম্মা রাব্বান নাসি আযহিবিল বা'স, ইশফিহী ওয়া আনতাশ শাফী, লা শিফা-আ ইল্লা শিফা-উকা, শিফা-আল লা ইয়ুগাদিরু সাক্বামা।",
    transliterationEn: "Allahumma Rabban-nasi adhhibil-ba's, ishfi wa Antash-Shafi, la shifa'a illa shifa'uk, shifa'an la yughadiru saqama.",
    translationBn: "হে আল্লাহ! হে মানুষের প্রতিপালক! কষ্ট দূর করে দিন, আরোগ্য দান করুন; আপনিই একমাত্র আরোগ্যকারী। আপনার আরোগ্য ছাড়া আর কোনো নিরাময় নেই—এমন আরোগ্য দিন যা কোনো রোগকে অবশিষ্ট রাখে না।",
    translationEn: "O Allah, Lord of mankind, remove the disease, cure him, for You are the Healer. There is no cure but Your cure, a cure that leaves no illness.",
    reference: "সহীহ বুখারী (৫৭৪২), সহীহ মুসলিম (২১৯১)",
    benefitBn: "রোগীর গায়ে হাত রেখে বা নিজের অসুস্থতার সময় পাঠ করে ফুঁ দেওয়া অত্যন্ত বরকতময় সুন্নাত।",
  },

  // Rizq & Debt Relief
  {
    id: "rizq-debt-relief-1",
    titleBn: "হালাল রিজিক ও পাহাড়সম ঋণ পরিশোধের দু'আ",
    titleEn: "Dua for Halal Rizq and Debt Relief",
    category: "rizq",
    categoryLabelBn: "রিজিক বৃদ্ধি ও ঋণমুক্তি",
    arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    transliterationBn: "আল্লাহুম্মাকফিনী বিহালালিকা 'আন হারামিকা, ওয়া আগনিনী বিফাদ্বলিকা 'আম্মান সিওয়াকা।",
    transliterationEn: "Allahummak-finee bihalaalika 'an haraamika, wa aghninee bifadlika 'amman siwaaka.",
    translationBn: "হে আল্লাহ! আমাকে আপনার হালাল রিযিক দিয়ে হারাম থেকে রক্ষা করুন এবং আপনার বিশেষ অনুগ্রহে আপনি ছাড়া অন্য সবার মুখাপেক্ষিতা থেকে আমাকে অভাবমুক্ত করুন।",
    translationEn: "O Allah, suffice me with what is lawful against what is prohibited, and make me independent of all those besides You by Your grace.",
    reference: "জামে তিরমিযী (৩৫৬৩) — হাসান হাদিস",
    benefitBn: "আলী (রাঃ) বলেন: যদি তোমার ওপর পাহাড় পরিমাণ ঋণও থাকে, আল্লাহ এই দু'আর বরকতে তা পরিশোধের ব্যবস্থা করে দেবেন।",
  },

  // Parents & Family
  {
    id: "family-parents-1",
    titleBn: "পিতা-মাতার জন্য রহমতের বিশেষ কুরআনী দু'আ",
    titleEn: "Dua for Mercy Upon Parents",
    category: "family",
    categoryLabelBn: "পিতা-মাতা ও পরিবার",
    arabic: "رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    transliterationBn: "রাব্বির হামহুমা কামা রাব্বায়ানী সাগীরা।",
    transliterationEn: "Rabbir-hamhuma kama rabbayanee sagheera.",
    translationBn: "হে আমার প্রতিপালক! তাঁদের উভয়ের প্রতি তেমনি দয়া করুন, যেমনি তাঁরা শৈশবে আমাকে স্নেহে লালন-পালন করেছিলেন।",
    translationEn: "My Lord, have mercy upon them as they brought me up when I was small.",
    reference: "সূরা বনী ইসরাঈল (১৭:২৪)",
    benefitBn: "পিতা-মাতা জীবিত কিংবা মৃত উভয় অবস্থায় তাঁদের জন্য প্রতিদিন নিয়মিত পাঠ্য।",
  },
]
